### PR TITLE
Make clear scan hooks documentation

### PR DESCRIPTION
**Pull request by teresanunez**
Scan Hooks documentation was not clear. Especially the difference between the Hooks API and the hooks being attached in the GSF generators.
I tried to clarify it keeping mainly what was there. Please check it and tell me if you prefer to add more
 documentation instead of modifying the existing one, as I did.
The links do not work, but for me the reason is a mystery ... they looks like correct.

### CODE REVIEW

**Comment by teresanunez** [comment]
Hi @reszelaz, many thanks !. I thought I have taken the new develop branch, I have probably
 made a mistake with some old directory.

**Comment by teresanunez** [comment]
Hi @reszelaz, one comment, you have replaced 'hints' by 'hook place' in the first paragraphs, but then you have left the word 'hint' from the setence 'The following is a list of hints ...' up to the end ... without any explanation about what is meant with 'hint'. Should not be any explanation or link pointed to it?.
Other small thing, the 'hooked_scan' link is  broken.

**Comment by reszelaz** [comment]
Ups, you are right. I just made the change from *hints* to *hook places* partially. I will finish this tomorrow and push directly to the repo.

Regarding the `hooked_scan` macro this is not a link but a name in monospace format. I decided to not autodocument the examples code but insert them literally to the examples chapter and put a link to this chapter.

**Comment by reszelaz** [comment]
I already corrected this chapter and now we always use the term of *hook place*. I had to reorder the things, so firts we talk about the *hook places* and the Hookable API, and later on we talk about he possibiltiy to register hooks in the `GScan` generator. Hope you like it.

**Pull request closed without merging**
