### PR TITLE
Allow changes of pseudo counter data format (shape)

### PR DESCRIPTION
**Pull request by reszelaz**
This feature was initiated by the #982 discussion. Now it is possible to define pseudo counters which returns a scalar, a spectrum or an image.

I tested it with the following trivial example:

```python

class ROI(PseudoCounterController):
    """A simple pseudo counter which receives an image from a 2D experimental
       channel and returns 1D of its first row"""

    counter_roles = "2D",

    def GetAxisAttributes(self, axis):
        axis_attrs = PseudoCounterController.GetAxisAttributes(self, axis)
        axis_attrs = dict(axis_attrs)
        axis_attrs['Value'][Type] = (float,)
        axis_attrs['Value'][MaxDimSize] = (1024,)
        return axis_attrs

    def Calc(self, axis, counter_values):
        i = counter_values[0]
        s = i[0]
        return s
```

It is very trivial, and assumes image of 1024 x 1024 pixels (for example the one provided by the `DummyTwoDController`).

This PR also includes the necessary documentation.

@sardana-org/integrators it is ready for the review and eventual integration.
Don't hesitate to ask if something does not work at first try. I made it in rush and tested it just with this simple example. Thanks!

### CODE REVIEW

**Comment by teresanunez** [comment]
Hi @reszelaz, many thanks for this implementation. I have started to test it and I have some comments:
1. perhaps you assume everybody would know ... but in the example the pseudo counter role is missed.
2. for me it is working if the counter is 2d and pseudo counter 1d, but with pseudo counter 2d is not working, it appears like 1d. I did it as you described in the documentation file of this PR ... perhaps
 I am setting something wrong. Have you tried it?.

Many thanks.

**Comment by reszelaz** [comment]
Thanks @teresanunez for the review!
There was a bug in the proposed documentation, and actually another one in the example povided in the initial PR comment.
The first one is that the `counter_roles` is a tuple - there was a comma missing.
The second one, is that in order to set a 2D value type you must use a typle with an intenal tuple containing the actual type: `((float, ), )`. The complete controller example could look like this:

```python
class ROI2D(PseudoCounterController):
    """A simple pseudo counter which receives an image from a 2D experimental
       channel and returns a 2D ROI after cropping one pixel frame"""

    counter_roles = "2D",

    def GetAxisAttributes(self, axis):
        axis_attrs = PseudoCounterController.GetAxisAttributes(self, axis)
        axis_attrs = dict(axis_attrs)
        axis_attrs['Value'][Type] = ((float, ), )
        axis_attrs['Value'][MaxDimSize] = (1024, 1024)
        return axis_attrs

    def Calc(self, axis, counter_values):
        i = counter_values[0]
        roi = i[1:-1, 1:-1]
        return roi
```

> perhaps you assume everybody would know ... but in the example the pseudo counter role is missed.

I thought that this was documented, but actually only the case of omitting the `counter_roles` is documented. I will add it to the documentation right now and will push it directly to the develop branch.

**Comment by reszelaz** [comment]
> I will add it to the documentation right now and will push it directly to the develop branch.

Done in: 23798d8

**Comment by teresanunez** [comment]
Many thanks, @reszelaz, I have tested it now again and IMO it can be merged.

**Comment by reszelaz** [comment]
Thanks! Merging it.

**Pull request merged**
