### PR TITLE
Extend repeat macro to run it easily from spock

### PR DESCRIPTION
**Pull request by teresanunez**
According to the discussion in #802, the syntax is implemented as:

Door> repeat 100 "ascan mot01 0 10 10 0.1" "ct 10" "dscan mot02 -20 20 6 0.2"

### CODE REVIEW

**Comment by dschick** [comment]
works as expected for me

**Comment by reszelaz** [comment]
Many thanks!

I do not know why but in my spock I have `repeat` name already reserved for the `numpy.repeat` function. In normal ipython I don't have it. This causes troubles when executing the macro. I need to proceed its name with `%` (explicitly call ipython's magic) I don't need to do it for other macros. Anyone else with this behavior?

Then, just to clarify, in case both parameters and hooks are set is it fine to execute only macros passed as parameters? I am not very decided about this and would like to know your opinions.

**Comment by reszelaz** [comment]
Thanks for the hint! I will check that.

**Comment by reszelaz** [comment]
This is the guilty one: https://github.com/sardana-org/sardana/blob/d8e9fbf28bf03d437f4fefd4c5e63b55ecb1f221/src/sardana/spock/ipython_01_00/genutils.py#L1124
When this line is commented the numpy object disappears from the namespace.

**Comment by reszelaz** [comment]
From IPython's documentation:

> TerminalIPythonApp.pylab : ‘auto’|’gtk’|’gtk3’|’inline’|’nbagg’|’notebook’|’osx’|’qt’|’qt4’|’qt5’|’tk’|’wx’
Pre-load matplotlib and numpy for interactive use, selecting a particular matplotlib backend and loop integration.

> TerminalIPythonApp.pylab_import_all : Bool
Default: True

> If true, IPython will populate the user namespace with numpy, pylab, etc. and an import * is done from numpy and pylab, when using pylab mode.

> When False, pylab mode should not import any names into the user namespace.

I think we need to set the second one to False. At least I think we don't need all these in the namespace. What do you think?

**Comment by teresanunez** [comment]
Hi @reszelaz, I also had this problem with the name repeat ... I made my tests calling it myrepeat.
Sorry, I thought it was working normally for all of you and it was a problem in my configuration.

**Comment by teresanunez** [comment]
About this:

""Then, just to clarify, in case both parameters and hooks are set is it fine to execute only macros passed as parameters? I am not very decided about this and would like to know your opinions.""

I am also not sure how to proceed. The advantage of making it like it is now:

-> if parameters are given the body hooks are ignored

is that one can reuse the macro without having to remove the body hooks. This could save time in some cases.

**Comment by teresanunez** [comment]
It is fine for me. Should I make the change or do you want to know more opinions before?

**Comment by reszelaz** [comment]
Maybe let's wait until tomorrow. Thanks a lot!

**Pull request merged**
