### PR TITLE
Release Jan19 (2.7.0)

### PR DESCRIPTION
**Pull request by daneos**
This is a PR to master for the official [Jan19 release](https://github.com/sardana-org/sardana/milestone/5). Final tests (automatic and manual) should be done based on it before accepting the merge.

So, this is a call for help from @sardana-org/integrators and any other person willing to help to test this branch ASAP in their respective systems.

For the moment the following systems are going to be tested thoroughly (feel free to add more to the list if you are willing to do the tests):

* [x] OpenSUSE 11.1 (#1055)
* [x] Debian 9 (#1056)
* [x] CentOS 7 (#1057)
* [x] Windows 10 (#1058)

Notes:
* A suggested check-list for the manual tests can be found in /doc/how_to_release.md
* The CI artifacts from this PR can be used for manual tests.
* If you do a full check using the check-list, please open an independent issue in order not to spam this PR with long comments
* If you want to paste long logs, consider using a [gist](https://gist.github.com/) for that.

### CODE REVIEW

**Comment by reszelaz** [comment]
I think it is convenient to cherry-pick solution for #1065. Ideally the said PR should be made to the release branch since this bug was discovered in the release tests. @teresanunez, @daneos do you agree? Will you do it? Or shall I do it?

**Comment by teresanunez** [comment]
Hi @reszelaz. yes, I agree. I can make the PR to the release branch.

**Comment by reszelaz** [comment]
> I can make the PR

It is enough to cherry-pick and push directly. I think it was only one commit..

**Comment by teresanunez** [comment]
Thanks, it is now done using cherry-pick.

**Comment by reszelaz** [comment]
I was going to approve this PR, but just realized that it is done for the develop branch and I think it shoudl be done for the master branch, right?

**Comment by daneos** [comment]
@reszelaz You're right, I changed the base branch, so it should be OK now.

**Comment by reszelaz** [comment]
Maybe better to wait for calrification of https://github.com/sardana-org/sardana/issues/1056#issuecomment-465617928.

**Comment by reszelaz** [comment]
> Maybe better to wait for calrification of #1056 (comment).

This one was already clarified.

**Pull request merged**
