### PR TITLE
Avoid errors when acquiring with offline controller

### PR DESCRIPTION
**Pull request by reszelaz**
An experimental channels from an offline controller does not export its
attributes. Then, it is not possible to obtain the Value attribute
configuration and an empty AttributeInfoEx is created for it. Its default
data_type is set to DevVoid. Handle this case and consider the
TangoChannelInfo with an unknown data_type. This avoids errors.

A change was proposed to Taurus that would avoid this PR: https://github.com/taurus-org/taurus/pull/666.

### CODE REVIEW

**Comment by reszelaz** [comment]
Thanks! I think it would be beneficial for the Taurus3 uesrs to keep it. I will just modify it to reflect that it only applies to Taurus3.

**Comment by reszelaz** [comment]
I've changed the code so it assumes to use Taurus 4.3 implementation and fallback for previous versions of Taurus. @mrosanes is going to test it.

**Comment by mrosanes** [comment]
If a controller cannot initialize correctly, the error message appearing when performing an acquisition with a given measurement group is more explicit right now using Taurus3 and also Taurus4:
<pre>
Cannot execute 'get_ctrl_par' because 'ctctrl...' is offline
</pre>

**Comment by reszelaz** [comment]
Great! Than I'm merging this PR.

**Pull request merged**
