### PR TITLE
not memorize measurement group attrs like integration time etc.

### PR DESCRIPTION
**Pull request by 13bscsaamjad**
Changed some attributes on measurement group to not be memorized.

### CODE REVIEW

**Review by reszelaz — APPROVED** [review]
When working on #1588 we realized that restoring the IntegrationTime's memorized value when some of the measurement group's controllers is _offline_ is problematic.

After quick reasoning, we think that IntegrationTime, MonitorCount, NbStarts, and SynchDescription should actually not be memorized. This is somehow _in conflict_ with the original design of Device Pool still available for reference in this [old document](https://github.com/sardana-org/sardana/blob/develop/doc/source/devel/api/tango_device_pool.rst):

> Integration_time, Integration_count, timer and monitor are memorized attributes. This means that the configuration values of these attributes are stored in the database. The next time the Pool starts the values are restored. This is done in order to reduce Pool configuration at startup to the minimum.

However, we believe this is outdated e.g. Timer and Monitor attributes were already removed and form part of the Configuration attribute which is memorized. We also believe that IntegrationTime and these other attributes are just related to a given acquisition and should not be stored persistently (we even doubt about the Moveable attribute).

Before merging it, it would be nice to hear other's opinions. Many thanks!

**Comment by reszelaz** [comment]
@sardana-org/integrators any comment on this one?

**Comment by teresanunez** [comment]
For me it is ok not having them memorized. I think it is not needed.

**Comment by reszelaz** [comment]
Thanks @teresanunez for your quick answer. I'm merging.

**Pull request merged**
