### PR TITLE
Fix macro function default settings

### PR DESCRIPTION
**Pull request by tiagocoutinho**
Make sure we return the exact same default settings as the Macro class
(ex: tools like the sequencer GUI expect hints to be a dict)

### CODE REVIEW

**Comment by reszelaz** [comment]
@tiagocoutinho, Many thanks for the PR! Could you please provide a macro example to reproduce this issue?

**Comment by tiagocoutinho** [comment]
Hi,
It should be reproducible when you have a simple macro function
```python
from sardana.macroserver.macro import macro

@macro()
def test(self):
    self.output("test")
```

and you try to launch it from the *sequencer* GUI application.

When we talked you said you cannot reproduce it. Could it be that the GUI became more robust and is now able to handle `hints=None` ?

IMHO, even if the GUI became more robust, I think is more correct that equivalent Macro class and macro function return the same macro information concerning the hints, param_def, result_def and env since there might be other clients that expect a more consistent API

**Comment by tiagocoutinho** [comment]
FYI, I notice that at ALBA MSPD beamline I had to apply this patch.
I cannot test now to go back to the previous version because they are running but I could do it on the Christmas shutdown. Hope it is not too late for you.

**Comment by reszelaz** [comment]
> When we talked you said you cannot reproduce it. Could it be that the GUI became more robust and is now able to handle `hints=None` ?

The sequencer GUI has not changed in this sense.
I managed to reproduce it! Before I was already using the macro function like you posted above, but I was adding it manually to the sequencer and this code was protected in the GUI.
Loading from the plain text file with the spock syntax (I think they use it a lot at BL04) was not protected and causing the error.
With your PR it gets fixed.

> 
> IMHO, even if the GUI became more robust, I think is more correct that equivalent Macro class and macro function return the same macro information concerning the hints, param_def, result_def and env since there might be other clients that expect a more consistent API

I agree with you, but I wanted to understand well the user scenario before merging the PR. Now I proceed with the merge.
Thanks a lot!

**Pull request merged**
