### PR TITLE
Improove error handling for state read

### PR DESCRIPTION
**Pull request by spirit1317**
Addressing this MAX-IV ticket: https://agile.maxiv.lu.se/project/vinhar-max-iv-machine-cs/us/4056 

Error in the controller layer need to be handled in the way that points to the actual error.

Now, when reading the state of an axis causes an error (eg. exception in StateOne) it will get printed to spock console, showing traceback with line of the error.

Screenshot from 2021-09-01 18-16-12

Please let me know if this is a sardana-friendly way.

### CODE REVIEW

**Review by reszelaz — COMMENTED** [review]
Thanks @spirit1317 for this contribution. It will become a great improvement in the debugging process.

I was trying it when running a `mv` with multiple moveables. For testing it I just uncomment this line:
https://github.com/sardana-org/sardana/blob/81ec9533da47346f114ac81ef00e1d943e6a7123/src/sardana/pool/poolcontrollers/DummyMotorController.py#L552

What I got is:

```
Door/zreszela/1 [2]: mv mot01 10 mot02 5
An error occurred while running mv:
RuntimeError: _mg_ms_20031_1 state is different than ON or ALARM. Can not proceed to start. Full information:
_mg_ms_20031_1:
       State: Fault (18:00:20.077505)
      Status: mot01 is in Fault
              mot02 is in Fault (18:00:23.079796)
    Position: [0. 0.]
Hint: in Spock execute `www`to get more details
```

While in case of a single moveable we get much more details:

```
Door/zreszela/1 [1]: mv mot01 10
An error occurred while running mv:
RuntimeError: mot01 state is different than ON or ALARM. Can not proceed to start. Full information:
mot01:
       State: Fault (17:53:55.715990)
      Status: mot01 is in Fault
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontroller.py", line 604, in raw_read_axis_states
                  state_info = ctrl.StateOne(axis)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 552, in StateOne
                  raise Exception("Cannot StateOne %d" % axis)
              Exception: Cannot StateOne 1 (17:53:58.720294)
    Position: 0.0
Hint: in Spock execute `www`to get more details
```

I was able to achieve a similar behavior using these [changes](https://github.com/reszelaz/sardana/commit/02b87ab5ceff1699dcaa3c8176f16b71320d7285):

```
Door_zreszela_2 [3]: mv mot19 10 mot20 5
Motion failed due to _mg_ms_22476_1 state is different than ON or ALARM. Can not proceed to start.
mot19:
       State: Fault (18:47:42.030684)
      Status: mot19 is in Fault
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontroller.py", line 604, in raw_read_axis_states
                  state_info = ctrl.StateOne(axis)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 552, in StateOne
                  raise Exception("Cannot StateOne %d" % axis)
              Exception: Cannot StateOne 3 (18:48:23.249933)
    Position: 0.0
mot20:
       State: Fault (18:48:20.235370)
      Status: mot20 is in Fault
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontroller.py", line 604, in raw_read_axis_states
                  state_info = ctrl.StateOne(axis)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 552, in StateOne
                  raise Exception("Cannot StateOne %d" % axis)
              Exception: Cannot StateOne 4 (18:48:23.251109)
    Position: 0.0
An error occurred while running mv:
RuntimeError: _mg_ms_22476_1 state is different than ON or ALARM. Can not proceed to start.
Hint: in Spock execute `www`to get more details
```

So something similar to what we were already doing in case of problems at the end of motion. I would propose to use this approach, but... it still does not work well when we run a single Sardana server. In this case, I get:

```
Door/zreszela/1 [1]: mv mot01 10
Motion failed due to: mot01 state is different than ON or ALARM. Can not proceed to start.
mot01:
       State: Fault (18:58:45.559545)
      Status: mot01 is in Fault
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/macroserver/macros/standard.py", line 533, in run
                  state, pos = motion.move(positions)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/motion.py", line 403, in move
                  ret = moveable.move(new_pos, timeout=timeout)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 1036, in go
                  PoolElement.go(self, *args, **kwargs)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 280, in new_fn
                  return fn(*args, **kwargs)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 531, in go
                  eid = self.start(*args, **kwargs)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 504, in start
                  raise e
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 490, in start
                  raise RuntimeError(
              RuntimeError: mot01 state is different than ON or ALARM. Can not proceed to start.
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontroller.py", line 604, in raw_read_axis_states
                  state_info = ctrl.StateOne(axis)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 552, in StateOne
                  raise Exception("Cannot StateOne %d" % axis)
              Exception: Cannot StateOne 1 (18:58:48.563324)
    Position: 0.0
An error occurred while running mv:
RuntimeError: mot01 state is different than ON or ALARM. Can not proceed to start.
Hint: in Spock execute `www`to get more details
```
as you can see, even for a single moveable. I will investigate this tomorrow, or maybe you have any clue on how to improve it (avoid this unncessary level of exception chaining)?

**Comment by reszelaz** [comment]
I managed to clear the context information ( _During handling of the above exception, another exception occurred:_)  from the traceback we attach to the status when Sardana is run as a standalone server.

For example, when we implement the following `StateOne()` method in the `BasicDummyMotorController` class:

```python
    def StateOne(self, axis):
        self._log.debug("StateOne(%d)", axis)
        try:
            try:
                raise ValueError("Low level error")
            except Exception as e:
                raise ValueError("High level error") from e
        except Exception as e:
            raise Exception("Cannot StateOne %d" % axis) from e
```
Now we get the following information in the case of running a `mv` with two dummies:

```
Door/zreszela/1 [2]: mv mot01 10 mot02 10
Motion failed due to: _mg_ms_20031_1 state is different than ON or ALARM. Can not proceed to start.
mot01:
       State: Fault (10:38:08.684911)
      Status: mot01 is in Fault
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 554, in StateOne
                  raise ValueError("Low level error")
              ValueError: Low level error
              
              The above exception was the direct cause of the following exception:
              
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 556, in StateOne
                  raise ValueError("High level error") from e
              ValueError: High level error
              
              The above exception was the direct cause of the following exception:
              
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontroller.py", line 609, in raw_read_axis_states
                  state_info = ctrl.StateOne(axis)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 558, in StateOne
                  raise Exception("Cannot StateOne %d" % axis) from e
              Exception: Cannot StateOne 1 (10:43:05.537853)
    Position: 0.0
mot02:
       State: Fault (10:43:02.524554)
      Status: mot02 is in Fault
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 554, in StateOne
                  raise ValueError("Low level error")
              ValueError: Low level error
              
              The above exception was the direct cause of the following exception:
              
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 556, in StateOne
                  raise ValueError("High level error") from e
              ValueError: High level error
              
              The above exception was the direct cause of the following exception:
              
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontroller.py", line 609, in raw_read_axis_states
                  state_info = ctrl.StateOne(axis)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 558, in StateOne
                  raise Exception("Cannot StateOne %d" % axis) from e
              Exception: Cannot StateOne 2 (10:43:05.539013)
    Position: 0.0
An error occurred while running mv:
RuntimeError: _mg_ms_20031_1 state is different than ON or ALARM. Can not proceed to start.
Hint: in Spock execute `www`to get more details
```
In order to do that, I needed to clear the `__context__` field of the exception (recursivelly).

I proposed a PR to your branch: https://github.com/spirit1317/sardana/pull/1. I think this is the way to go, what do you think?  Also, please verify it still works as expected to you. Then I think this PR would be ready to be merged.

**Comment by spirit1317** [comment]
Hello,
Thanks, it seems to be working as expected. If I understand correctly, similar thing will have to be done if we want to show those errors for scan macros:
```sh
Door_mc_1 [30]: a2scan mot01 0 1 mot02 0 1 1 1
ScanDir is not defined. This operation will not be stored persistently. Use "expconf" or "newfile" to configure data storage (or eventually "senv ScanDir <abs directory>")
Scan #4 started at Thu Sep  9 18:00:40 2021. It will take at least 0:00:02.282843
Report: Stopped at step #0 with:
_mg_ms_8193_1:
       State: Fault (17:04:54.486863)
      Status: mot01 is in Fault
              mot02 is in Fault (18:00:53.608330)
    Position: [0. 0.]
Scan #4 ended at Thu Sep  9 18:00:53 2021, taking 0:00:12.954539. Dead time 62.9% (setup time 37.1%, motion dead time 0.0%)
An error occurred while running a2scan:
RuntimeError: _mg_ms_8193_1 state is different than ON or ALARM. Can not proceed to start.
Hint: in Spock execute `www`to get more details

Door_mc_1 [31]: www
Traceback (most recent call last):
  File "/home/mateusz/Documents/sardana/src/sardana/macroserver/msmacromanager.py", line 1676, in runMacro
    for step in macro_obj.exec_():
  File "/home/mateusz/Documents/sardana/src/sardana/macroserver/macro.py", line 2362, in exec_
    for i in it:
  File "/home/mateusz/Documents/sardana/src/sardana/macroserver/macros/scan.py", line 291, in run
    for step in self._gScan.step_scan():
  File "/home/mateusz/Documents/sardana/src/sardana/macroserver/scan/gscan.py", line 1061, in step_scan
    for i in self.scan_loop():
  File "/home/mateusz/Documents/sardana/src/sardana/macroserver/scan/gscan.py", line 1164, in scan_loop
    self.stepUp(i, step, lstep)
  File "/home/mateusz/Documents/sardana/src/sardana/macroserver/scan/gscan.py", line 1193, in stepUp
    state, positions = motion.move(step['positions'])
  File "/home/mateusz/Documents/sardana/src/sardana/taurus/core/tango/sardana/motion.py", line 403, in move
    ret = moveable.move(new_pos, timeout=timeout)
  File "/home/mateusz/Documents/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 1260, in go
    PoolElement.go(self, *args, **kwargs)
  File "/home/mateusz/Documents/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 280, in new_fn
    return fn(*args, **kwargs)
  File "/home/mateusz/Documents/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 531, in go
    eid = self.start(*args, **kwargs)
  File "/home/mateusz/Documents/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 280, in new_fn
    return fn(*args, **kwargs)
  File "/home/mateusz/Documents/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 504, in start
    raise e
  File "/home/mateusz/Documents/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 491, in start
    "{} state is different than ON or ALARM. Can not proceed to start.".format(self.name))
RuntimeError: _mg_ms_8193_1 state is different than ON or ALARM. Can not proceed to start.
```

**Comment by spirit1317** [comment]
There's also one thing I don't quite get - this context clearing.

```
Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/macroserver/macros/standard.py", line 533, in run
                  state, pos = motion.move(positions)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/motion.py", line 403, in move
                  ret = moveable.move(new_pos, timeout=timeout)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 1036, in go
                  PoolElement.go(self, *args, **kwargs)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 280, in new_fn
                  return fn(*args, **kwargs)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 531, in go
                  eid = self.start(*args, **kwargs)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 504, in start
                  raise e
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 490, in start
                  raise RuntimeError(
              RuntimeError: mot01 state is different than ON or ALARM. Can not proceed to start.
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontroller.py", line 604, in raw_read_axis_states
                  state_info = ctrl.StateOne(axis)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 552, in StateOne
                  raise Exception("Cannot StateOne %d" % axis)
              Exception: Cannot StateOne 1 (18:58:48.563324)
```

The context of `Exception("Cannot StateOne %d" % axis)` was `RuntimeError: mot01 state is different than ON or ALARM.`. The exception in StateOne was first, shouldn't it be:

```
Exception: Cannot StateOne 1
              
              During handling of the above exception, another exception occurred:

RuntimeError: mot01 state is different than ON or ALARM. Can not proceed to start.
```

Also, `StateOne` exception is catched [here](https://github.com/sardana-org/sardana/blob/develop/src/sardana/pool/poolcontroller.py#L611), then formatted and returned without re-raising before [this exception](https://github.com/spirit1317/sardana/blob/95bfadede5f5f13337aeaa8d3942de5578790302/src/sardana/taurus/core/tango/sardana/pool.py#L490) happens. So why are both connected by `__context__`?

I'd like to understand this because I could work with some other sardana exception handling issues then.

**Comment by reszelaz** [comment]
> If I understand correctly, similar thing will have to be done if we want to show those errors for scan macros:

Yes, I would leave it to the macro developer to decide on how to show the _debug information_. The case you point would require the following change in `sardana.macroserver.scan.gscan`:

image

With this I obtain:

```
Door/zreszela/1 [1]: a2scan mot01 0 1 mot02 0 1 1 0.1
Operation will be saved in /tmp/scans.h5 (HDF5::NXscan from NXscanH5_FileRecorder)
Scan #6 started at Thu Sep  9 18:40:59 2021. It will take at least 0:00:00.647214
Report: Stopped at step #0 with:
mot01:
       State: Fault (18:40:39.461527)
      Status: mot01 is in Fault
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontroller.py", line 608, in raw_read_axis_states
                  state_info = ctrl.StateOne(axis)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 552, in StateOne
                  raise Exception("Cannot StateOne %d" % axis)
              Exception: Cannot StateOne 1 (18:41:02.497413)
    Position: 0.0
mot02:
       State: Fault (18:40:39.470502)
      Status: mot02 is in Fault
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontroller.py", line 608, in raw_read_axis_states
                  state_info = ctrl.StateOne(axis)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 552, in StateOne
                  raise Exception("Cannot StateOne %d" % axis)
              Exception: Cannot StateOne 2 (18:41:02.498595)
    Position: 0.0
Operation saved in /tmp/scans.h5 (HDF5::NXscan)
Scan #6 ended at Thu Sep  9 18:41:02 2021, taking 0:00:03.029002. Dead time 99.7% (setup time 0.3%, motion dead time 0.0%)
An error occurred while running a2scan:
RuntimeError: _mg_ms_20031_1 state is different than ON or ALARM. Can not proceed to start.
Hint: in Spock execute `www`to get more details

```

I just realized we should also think about how we want to dump information on pseudo motors. Now it is as following:

```
Door/zreszela/1 [2]: ascan offset01 0 1 1 0.1
Operation will be saved in /tmp/scans.h5 (HDF5::NXscan from NXscanH5_FileRecorder)
Scan #7 started at Thu Sep  9 18:46:45 2021. It will take at least 0:00:00.200000
Report: Stopped at step #0 with:
offset01:
       State: Fault (18:46:45.012548)
      Status: offset01 is in Fault
              mot01 is in Fault
              mot02 is in Fault (18:46:48.046579)
    Position: 0.0
Operation saved in /tmp/scans.h5 (HDF5::NXscan)
Scan #7 ended at Thu Sep  9 18:46:48 2021, taking 0:00:03.026229. Dead time 99.5% (setup time 0.5%, motion dead time 0.0%)
An error occurred while running ascan:
RuntimeError: offset01 state is different than ON or ALARM. Can not proceed to start.
Hint: in Spock execute `www`to get more details
```

Maybe in this case it would be also interesting to show the status of the base elements, in this case, `mot01` and `mot02`? We need to remember that the base element hierarchy may be of multiple levels. Or you think it could get too complicated and overwhelming to the user? An idea for the implementation could be to use recursive calls in `sardana.taurus.core.tango.sardana.pool.PseudoMotor._information()` and indentation when printing info in order to improve readability.

**Comment by reszelaz** [comment]
> The context of Exception("Cannot StateOne %d" % axis) was RuntimeError: mot01 state is different than ON or ALARM.. 

I agree.

> The exception in StateOne was first, shouldn't it be:
> ```
> Exception: Cannot StateOne 1
>              
>               During handling of the above exception, another exception occurred:
> 
> RuntimeError: mot01 state is different than ON or ALARM. Can not proceed to start.
> ```

I think it is the other way around. We are in except clause of the RuntimeError when we read the state and it fails. So, _during handling of the RuntimeError another exception (the one fron the StateOne()) occured_. IMO this was correct:

```
              mot01 is in Fault
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/macroserver/macros/standard.py", line 533, in run
                  state, pos = motion.move(positions)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/motion.py", line 403, in move
                  ret = moveable.move(new_pos, timeout=timeout)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 1036, in go
                  PoolElement.go(self, *args, **kwargs)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 280, in new_fn
                  return fn(*args, **kwargs)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 531, in go
                  eid = self.start(*args, **kwargs)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 504, in start
                  raise e
                File "/homelocal/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 490, in start
                  raise RuntimeError(
              RuntimeError: mot01 state is different than ON or ALARM. Can not proceed to start.
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontroller.py", line 604, in raw_read_axis_states
                  state_info = ctrl.StateOne(axis)
                File "/homelocal/zreszela/workspace/sardana/src/sardana/pool/poolcontrollers/DummyMotorController.py", line 552, in StateOne
                  raise Exception("Cannot StateOne %d" % axis)
              Exception: Cannot StateOne 1 (18:58:48.563324)
```

> Also, StateOne exception is catched here, then formatted and returned without re-raising before this exception happens. So why are both connected by __context__?

This is because when you run Sardana as a standalone server the same python interpreter handles both the Pool and the MacroServer and the exception raised in the macro code is seen as the context when handling the exceptions raised in `StateOne()`. I think we don't want this to appear in the traceback, that's why I introduce the hack to clear it. It also explains why when you run Pool and MacroServer as independent processes the traceback we attach to the status is clear already.

At least this is how I interpret it, I hope to not confuse you more:)

**Comment by spirit1317** [comment]
Hi again. Is this PR ready to be merged?

I introduced your changes to:
https://github.com/spirit1317/sardana/pull/1

I assume you don't want me to add this change:
https://github.com/sardana-org/sardana/pull/1685#issuecomment-916279126

?
thanks

**Comment by reszelaz** [comment]
> I introduced your changes to:
> [spirit1317#1](https://github.com/spirit1317/sardana/pull/1)

Thanks!

> I assume you don't want me to add this change:
> [#1685 (comment)](https://github.com/sardana-org/sardana/pull/1685#issuecomment-916279126)

No, this comment was to trigger a broader discussion in the community, but since there were no comments, let's postpone it. 

So, for me it is ready. I just pushed ef1ba27 to better dump info on scans as was discussed in https://github.com/sardana-org/sardana/pull/1685#issuecomment-916279126. I will merge after a successful execution of tests.

Thanks again for your contribution!

**Pull request merged**
