### PR TITLE
Add repeat macro to standard macros

### PR DESCRIPTION
**Pull request by reszelaz**
Add repeat macro (from third-party repository:
https://sourceforge.net/p/sardana/macros.git/ci/master/tree/ALBA_GENERAL/tools.py).
Fix issue-308.

Just after integrating it we should add a comment in the third-party repo that this was moved to the standar macros.

@dschick could you test it?

### CODE REVIEW

**Comment by dschick** [comment]
I can try testing it within the next days. Do you rely on any test framework or are you asking me more for a real-world testing?

**Comment by reszelaz** [comment]
We have test framework for some part of the code but I have not added any tests for this macro in order to integrate it fast for your needs. Actually, this macro is used quite often at Alba - I do not expect problems..

**Comment by teresanunez** [comment]
I have tested it with the sequencer and in spock (adding a general hook in the position 'body') and
 it works fine.

**Comment by reszelaz** [comment]
Thanks for the review @teresanunez. I'm merging it..

**Pull request merged**
