### PR TITLE
respect timer/monitor passed in measurement group configuration

### PR DESCRIPTION
**Pull request by reszelaz**
timer/monitor configuration parameters are still kept in the measurement
group configuration for the backwards compatibility. Respect the user
configuration values (if present) otherwise fill it with the software
master timer/monitor or a random timerable channel (last fallback).

### CODE REVIEW

**Comment by jkotan** [comment]
Hi Zibi,
One needs to add 
```patch
diff --git a/src/sardana/pool/poolmeasurementgroup.py b/src/sardana/pool/poolmeasurementgroup.py
index 98675a96e..951bed937 100644
--- a/src/sardana/pool/poolmeasurementgroup.py
+++ b/src/sardana/pool/poolmeasurementgroup.py
@@ -868,6 +868,7 @@ class MeasurementConfiguration(object):
         # Fill user configuration with measurement group's timer & monitor
         # This is a backwards compatibility cause the measurement group's
         # timer & monitor are not used
+        self._timerable_ctrls = timerable_ctrls
         mnt_grp_timer = cfg.get('timer')
         if mnt_grp_timer:
             timerable_channels = self.get_timerable_channels(enabled=True)
```
to fix the issue mentioned in #1516

**Comment by reszelaz** [comment]
Thanks for pointing this out. You are right `MeasurementConfiguration._timerable_ctrls` are still not updated at the point where we are looking for the timer/monitor. IIRC this was done on purpose to update the local members at the very end of the setting process. What we wanted to achive is that in the case the new configuration is not correct we raise an exception and leaves the object in an untouched state. Because of that, instead of directly applying your suggestion, I decided to refactor the code a little bit and use another approach in order to avoid prematurely setting the `MeasurementConfiguration._timerable_ctrls`. But I think it should aboid the problem you experienced.

Before you invest your time in testing it again, let's wait for the CI results. When this get's green, go ahaead with your tests (I have only tested very simple cases).

Many thanks for your help!

**Comment by reszelaz** [comment]
@jkotan CI gives us green light already. 

Please remember:

> But if I understands well, what is currently in that PR (now it simply returns in the configuration what was passed when settin it) won't be enough. What you actually would like is that the channels set as master timer/monitor are started as the last ones? In this case we would also need to set them as master timer/monitor for the software synchronization. If you confirm I will make an additional commit.

from https://github.com/sardana-org/sardana/issues/1516#issuecomment-797535167

**Comment by jkotan** [comment]
Great. Thanks! I've just tested and it works it fixes the issue #1516. 

> What you actually would like is that the channels set as master timer/monitor are started as the last ones?

Here, I'm confused. I don't see the reason why timer should be started at the end unless you have big differences between starting different channels.

**Comment by jkotan** [comment]
I've talked to Teresa and we don't need the feature which the channels set as master timer/monitor are started as the last ones

**Comment by reszelaz** [comment]
I thought that you need to specify the master timer/monitor of the measurement group for the need of the ordered start. If this is not the case, what do you use this information for?

I don't know your setup and I may be completely wrong, but I was imagining that in the same measurement group you have some counter channels proceeding from one hardware controller (is it SIS3820?) and a timer channel proceeding from a different hardware controller (is it DGG2?). I imagine that counters count only when the timer gives a gate signal to them. In this case, counters need to be started (armed) for the acquisition in the first order and the timer must be only started as the last one.
Please correct my thinking. Many thanks!

**Comment by jkotan** [comment]
Hi Zibi, 
All the details  can explain to you by Teresa online.
The master timer/monitor configuration is used in our user applications, It is need to know what is the master timer. Also the right order in measurement group is required by some text-file data recorders. Also in spock some our users want to have specific order of channels.  

With counters and timers everything works OK. Teresa has implemented it in sardana.
Our counters (sis3820) are connected to timer (dgg2) via cable. The timer sends to counters a gate signal. The counter don't have to be started, only reset is needed. The general procedure is:
```python
resetCounter()
timer.sampleTime = sampleTime
startTimer()
waitForTimer()
readCounter()
```

**Comment by reszelaz** [comment]
> The master timer/monitor configuration is used in our user applications, It is need to know what is the master timer. Also the right order in measurement group is required by some text-file data recorders. Also in spock some our users want to have specific order of channels.

Thanks for the clarification! Now I see the use cases.
So, you use measurement group configuration, as a place to store information about the master timer channel. 

I also agree that the order of channels used as the mechanism to select the master timer is limiting us. It's better to add a more explicit and flexible way to select it. And actually, we need two master timers: one for the software trigger and gate, and another one for the software start. But, better to open a dedicated issue to discuss it. 


> With counters and timers everything works OK. Teresa has implemented it in sardana.
> Our counters (sis3820) are connected to timer (dgg2) via cable. The timer sends to counters a gate signal. The counter don't have to be started, only reset is needed. The general procedure is:
> 
> ```python
> resetCounter()
> timer.sampleTime = sampleTime
> startTimer()
> waitForTimer()
> readCounter()
> ```

Yes, it works well, I was looking into these controllers' code and I see that you use the `PreStartOne()` to call the reset on the sis3820 and the `StartAll()` to call start on the dgg2. According to [Multiple acquisition synchronization](https://sardana-controls.org/devel/howto_controllers/howto_countertimercontroller.html#multiple-acquisition-synchronization) this is enought to ensure the order that you need. 

With your confirmation that it works as expected, I proceed to auto-merge.

**Pull request merged**
