### PR TITLE
Issue #458: IORegisterController WriteOne method gives a integer as value

### PR DESCRIPTION
**Pull request by rhomspuron**
This is a possible solution for the bug.

### CODE REVIEW

**Comment by teresanunez** [comment]
Hi, I have had a look at this and the issue with float/long is solved. What I see is (but it was already like this) that if I write the attribute Value with a ATK panel open, Value is not updated until I read it from
 any other client. It seems that  there is something wrong with the events. Could you check if you also see something strange there?. Thanks.

**Comment by reszelaz** [comment]
What @teresanunez describes must be related to https://github.com/sardana-org/sardana/issues/21.
I think that the `PoolIORAcquisition` is never started, so no one checks the state neither update the value and its quality. Anyway I would treat it as a separate issue.

Regarding the `Value` type, you went for the double and not for the integer. Do you have in mind any IOR's where integer in not enough?

Finally, I was also looking at the TANGO new attribute type `DevEnum`, whigh sounds interesting from the IOR `Value` attribute point of view. The only thing is that its values must be consecutive integers starting from 0...  And I think that in Sardana we would like to maintain a free choice of the IOR `Value`. But personally, I have never used this new attribute type, is there anyone with more experience?

**Comment by rhomspuron** [comment]
The IOR can be used to control a motor, in this case the the value should be a double, in other words, the DiscretePseudoMotorController could be controller with the IOR. 

The value can be an integer, but in this case its meaning change from value to index like the DevEnum or the case of the TangoAttrIORCtrl, we should decide if the value is an index of a list of values or it is the value which we wants to write in the hardware.

**Comment by reszelaz** [comment]
Yes, we need to agree on the IOR interface. As a baseline analysis we could start from reviewing of what we have already in the [controllers repository](https://sourceforge.net/p/sardana/controllers.git/ci/master/tree/python/ioregister/) and contacting the authors and asking them what is missing in the current interface or how it could be improved. Meanwhile let me start brainstorming...

From the one hand, we could interpret the IOR as a generic element which allows to write/read from a given hardware register a value. This value may be of any type: integer, float, boolean (maybe string as well?) but the hardware usually expects a fixed type for a given register. In the Sardana core, the attribute does not have any type associated to it (at least yet). The type definition that started the whole discussion is used so far by the Tango layer only. Ideally, the IOR `Value` Tango attribute type should not be fixed but dynamic allowing to specify a different type for each IOR axis. This is already possible for the Motor `Position` attribute so I think that we should also allow that for the IOR `Value` attribute. The IOR generic widget could benefit from that providing a specific write/read subwidget.
The controller developer just needs to override the [GetAxisAttributes](https://github.com/sardana-org/sardana/blob/develop/src/sardana/pool/controller.py#L481) method. Some small development would be still necessary to make it work for the IOR. The Motor’s [implementation](https://github.com/sardana-org/sardana/blob/develop/src/sardana/tango/pool/Motor.py#L423) could serve as an inspiration.

So I refine my question, what should be the default type of the IOR `Value` attribute? This has also an impact on the `write_ioreg` macro argument type.

Following this definition of the IOR we should keep in mind that creating an IOR for each register of a hardware controller would mean creating many Pool elements, what in the Tango world also implies many Tango devices. This would allow to control the write process with an action (thread), and having a state associate to each register. An alternative solution would be to use the axis extra attributes of an element. We should document the pros and cons of each of this approaches.

From the other hand it may be interesting to, instead of operating the IOR with the raw values, operate it with the more meaningful value descriptions. At Alba we do it with the [TangoAttributeIORCtrl](https://sourceforge.net/p/sardana/controllers.git/ci/master/tree/python/ioregister/TangoAttrIORCtrl.py). Since we are already discussing the IOR interface maybe it is a good moment to think, if it has sense to include the required logic (calibration and labels) in the generic IOR interface. Again, the IOR generic widget could benefit from that providing a specific write/read subwidgets. My previous comment about the `DevEnun` type is related to that. What are your opinions about it?

Regarding changes of the attribute default type we have made a similar change for the [DiscetePseudoMotorController](https://github.com/sardana-org/sardana/blob/develop/src/sardana/pool/poolcontrollers/DiscretePseudoMotorController.py). Which I think was not necessary. I have reverted 7add752 and it does not provoke any problems with the `mv` macro as stated in #92. @rhomspuron and @saggiss could you cross-check it, please?

**Comment by reszelaz** [comment]
I have submitted https://github.com/rhomspuron/sardana/pull/1 that allows to freely change the IOR `Value` data type between `int`, `float` and `bool`. With this, I think that we could change the default IOR `Value` data type to double as you suggest. The only missing thing would be to change the macro parameter type of `write_ioreg` and the macro result type of the `read_ioreg` from `Integer` to `Double`. This way these macros will compatible with any type of IOR.

Note that it would be trivial to add one more possible data type `str`. Does anyone see it interesting? If there are no voices I will keep just the three types for the moment.

**Comment by teresanunez** [comment]
Up to now we have not had any request for the str type there.

**Comment by reszelaz** [comment]
Let's leave the `str` data type out of the scope of this feature request.

Now, the `read_ioreg` macro result is of type `Float`. But I think that we could refactor this macro in order to follow the `wm` behavior. That means, to print via the door output the IOR value instead of using the magic command output. This way we could print the value respecting its data type e.g. 1, 99.9 or True. But this is of course out of the scope of this PR. Just some idea for the future. 

I think that everything is already implemented so I'm proceeding with the merge.

**Pull request merged**
