### PR TITLE
SEP2 - Improve integration of 1D and 2D experimental channels

### PR DESCRIPTION
**Pull request by reszelaz**
Even if there are no changes in this PR yet I already start it so we have a place for discussions.

The current [SEP2](https://github.com/reszelaz/sardana/blob/sep2/doc/source/sep/SEP2.md) document requires modifications.
This branch will also serve for future implementation.

### CODE REVIEW

**Comment by reszelaz** [comment]
# Current implementation

* It is possible to execute single acquisition measurement e.g. ct, step scans with 1D and 2D detectors.
* In the measurement group one could use either channel or channel + its `Datasource` attribute.
* Data source is by default composed by Sardana, but could be returned by the controller with `GetPar` method.
* Data is transferred via `Value` attribute readout.
* Data source is transferred via `Datasource` attribute readout.
    ~~~
    Door> defmeas mntgrp-2d ct01 oned01 twod01 oned01/datasource twod01/datasource
    Door> ct
    Door> ascan mot01 0 1 1 0.1
    ~~~
* H5 recorder:
    * 1D and 2D are correctly stored in the file:
    ```python
    import h5py
    h5py.File("<path-to-file>").items()[-1][1]["measurement"]["twod01"][0]`
    ```
    * Data source is not stored in the file:
    ```python
    import h5py
    h5py.File("<path-to-file>").items()[-1][1]["measurement"].keys()
    ```
* Spec recorder:
    * 1D is stored in the file, 2D is not stored in the file
    * Data source is correctly stored in the file:
    ```
    $> tail <path-to-file>
    ```
* Output recorder:
    * 1D and 2D are displayed as their shapes
    * Data source is not displayed, just  `<string>` placeholder is displayed

* It is possible to execute multi acquisition measurement e.g. continuous scan, timescan with 1D detectors.
    * In this case only data is transferred via `Data` attribute events (index + 1D)

**Comment by reszelaz** [comment]
# Design ideas
(gathered during Alba internal brainstorming)

* How to extract and transfer data/datasource:
    * Controller will have two possibilities: either return data (`Readable` interface) or data source (also 
    `Readable` interface and distinguish the type in the core? another interface? `GetPar`?)
    * 2D data should be passed via `Data` attribute events (as it is done for the 1D)
    * How to pass data source? Via `Data` attribute events?

* Recorders:
    * Output
        * Hyperlink with image name e.g. sample1_000.edf
    * H5
        * String with URI
        * If H5 format is used we could provide links (virtual data sets)? Anyone interested in this?

* Saving configuration:
    * On channel level
        * Directory
        * Prefix
        * Suffix
        * Index format
        * Override policy
        * Active saving (bool)
    * On experiment configuration level or measurement group level (configuration)
        * Example: the same detector may be used in two different configurations e.g. raster scan (heat map) and data collection.
    * This should include all the attributes configurable on the channel level

* Widgets:
    * ExpChannel widget
        * Label with context menu with Tango Attributes
        * Read value / button with link/image/array
        * Integration time
        * Start/Stop action
    * Expconf
        * We need to add the saving configuration
        * We could take a profit and remodel this widget

**Comment by reszelaz** [comment]
At ALBA we have prepared an early draft of SEP2. It would be nice if you could review it and provide feedback before the next week. The plan is to start working on it soon...

In the SEP2 there are few TODOs, mainly about choosing the best names. Please express your preferences or even propose new names.

I plan to create a dedicate project board with the implementation tasks so it will be easier to coordinate work with anyone interested to contribute.

**Comment by reszelaz** [comment]
At Alba we have though more about the naming and terminology being introduced by SEP2. The following table summarizes the new concepts and the names currently proposed in the SEP2 docuement as well as a set of alternative names.

| Concept | SEP2 name | Alternative name |
| ------- | --------- | ----------------- |
| channel/controller capability to report reference(s) to the data | saving capability | referencing capability |
| channel attribute that exposes reference to the data | ValueSource | ValueRef |
| channel attribute that exposes the chunks with multiple data references | ValueSourceBuffer | ValueRefBuffer |
| channel attribute to set the ideal place to store the data | ValueSourceTemplate | ValueRefTemplate |
| channel attribute to enable/disable storing the data externally and reporting the reference to the data, for example "saving" | SavingEnable | ValueRefEnabled |
| controller interface (to inherit from it) indicating that the controller is able to report data references | Sourceable | Referable |
| controller method to report data source | SourceOne | RefOne |

After some internal discussions we are more in favor of the alternative names. If you have preferences please comment, of course, we are open for new proposals. Otherwise I will proceed to update the SEP2 document.

**Comment by reszelaz** [comment]
SEP2 developments are finally approaching the end:) There are some things that I would like to share with you and ask for your feedback.

I think that [Scan framework API for referencing configuration](https://github.com/reszelaz/sardana/blob/sep2/doc/source/sep/SEP2.md#scan-framework-api-for-referencing-configuration) could be finally kept out-of-scope of SEP2. To me this is a kind of top-level/facilitating configuration API which can be added at any time. So just to speed-up integration of SEP2 let's keep it out. Do you agree?

Later there are some points regarding the API, more preciselly [changes in the current implementation](https://github.com/reszelaz/sardana/blob/sep2/doc/source/sep/SEP2.md#changes-in-the-current-implementation):

Is there anyone using the old *data source* feature (points 1 and 2)? If you think this was never used I propose to not even provide the backwards compatibility layer and directly remove them. What is your opinion?

In case of the 0D experimental channel the renaming of `Data` attribute to `ValueBuffer` (point 3) actually implies the change of the meaning of the `ValueBuffer` attribute. This attribute was marked as deprecated in 2.3.0 when it was recommended to use the `AccumulationBuffer`. I doubt that this attribute was actullay used... So I wonder if we could all agree to overlook the [semantic versioning](https://semver.org/) in this case. What is your opinion?

**Comment by teresanunez** [comment]
Hi Zibi,

> SEP2 developments are finally approaching the end:) There are some things that I would like to share with you and ask for your feedback.
> 
> I think that [Scan framework API for referencing configuration](https://github.com/reszelaz/sardana/blob/sep2/doc/source/sep/SEP2.md#scan-framework-api-for-referencing-configuration) could be finally kept out-of-scope of SEP2. To me this is a kind of top-level/facilitating configuration API which can be added at any time. So just to speed-up integration of SEP2 let's keep it out. Do you agree?
> 

Yes, I agree.

> Later there are some points regarding the API, more preciselly [changes in the current implementation](https://github.com/reszelaz/sardana/blob/sep2/doc/source/sep/SEP2.md#changes-in-the-current-implementation):
> 
> Is there anyone using the old _data source_ feature (points 1 and 2)? If you think this was never used I propose to not even provide the backwards compatibility layer and directly remove them. What is your opinion?

We are using data_source in some of our controllers. If a backwards compatibility can be 
implemented it would be better for us. If not we should try to change it.

> 
> In case of the 0D experimental channel the renaming of `Data` attribute to `ValueBuffer` (point 3) actually implies the change of the meaning of the `ValueBuffer` attribute. This attribute was marked as deprecated in 2.3.0 when it was recommended to use the `AccumulationBuffer`. I doubt that this attribute was actullay used... So I wonder if we could all agree to overlook the [semantic versioning](https://semver.org/) in this case. What is your opinion?

i do not think that we use that attribute, perhaps some user clients, but I hope it will not be a problem.
It should be fine if you make the changes you propose there.

**Comment by reszelaz** [comment]
>> We are using data_source in some of our controllers. If a backwards compatibility can be
implemented it would be better for us. If not we should try to change it.

> Then I will try to provide the backwards compatibility.

Done in 0a935f1.

**Comment by teresanunez** [comment]
Thanks, @reszelaz.
 We use still the old interface for LoadOne, but if you remove the deprecation I would change the
 controllers, no problem (I even think that it is better that I change them in any case).

**Comment by reszelaz** [comment]
I think that all the SEP2 scope is already covered in the implementation, hooray!:)
The last notice is that based on https://github.com/sardana-org/sardana/pull/775#issuecomment-490449249 I removed the *Scan framework API for referencing configuration* from the scope.

Now it would be nice if you could give it a try and feedback first impressions on how it works in the reality. Unfortunatelly there is no documentation apart from the SEP itself. Hopefully on the comming soon documentation camp we could add something... There is the [DummyTwoDController](https://github.com/reszelaz/sardana/blob/sep2/src/sardana/pool/poolcontrollers/DummyTwoDController.py) which is complete (covers all the possible synchronization modes and both value and value reference reporting) but at the same time may be too complicated...

I think that @rhomspuron is willing to start working on LimaTwoDController following SEP2. If there is anyone interested in joinining this effort I encourage you to contact with him. For the purpose of this development we could start a dedicated project on GitHub (or whatever other public platform) so we could also test the idea of having Sardana plugins in distributed repositories ([SEP16](https://github.com/sardana-org/sardana/pull/726)), what do you think?

And finally there is still one decission to be taken (we could discuss it on tomorrow's follow-up meeting):
* In the case of the 0D experimental channel we renamed the Data attribute to ValueBuffer previously reserved for the current AccumulationBuffer. Should we bump the major version for that? If yes what do we do with the already deprecated features?

**Comment by teresanunez** [comment]
Hi @reszelaz, I have done some tests and for me it looks fine. I have also tried my old twoD controllers, 
to check if they work like before, and it looks fine. If there is any specific thing that you want me to test just tell me.

**Comment by reszelaz** [comment]
Thanks for your tests @teresanunez!

Some ideas which comes to my mind about the tests are:

* Single channel acquisition (`ct` macro with channel as parameter) with and without value reference reporting. Also try different value reference patterns. 
* Measurement group acquisition (`ct` macro with measurement group as parameter) with and without value reference reporting. Also try different value reference patterns. This could be tested with different synchronization modes (all but software gate which is still not implemented in sardana).
* Scans (step and continuous) with and without value reference reporting. These could be tested with different synchronization modes (all but software gate which is still not implemented). When source file is an HDF5 file (`h5file` scheme), and the HDF5 library both with h5py supports VDS, the sardana scan file should create VDS.
* Pseudo counters are possible to be build on top of 2D even if it reports value references.

All the above tests are possible with the dummy 2D but of course would be better to do with some custom controller. Also in the measurement group I would include a dummy C/T and a 0D to check if there are no regressions.

@amilan, @daneos, do you see it feasible to vote this SEP before the end of next week. It would be great to make the Sardana Workshop with SEP2 integrated in develop, of course if you see it acceptable.

**Comment by teresanunez** [comment]
@reszelaz, one thing that I have just now observed (I guess I do something wrong),
 if I have a 2D in th MG and run ascan or ct without given an exp channel as argument, the
 ValueRef is never updated with what i write in ValueRefPattern ... but if without changing
 anything I run ct giving the 2D as argument, the ValueRef is updated with what is written
 ValueRefPattern.

**Comment by teresanunez** [comment]
Hallo @reszelaz, another comment, the Pool is constantly throwing the error:

Dummy-1        WARNING  2019-05-22 12:37:30,907 twod05: data_source is deprecated since version Jul19. Use value_ref instead.
ddddddddddddddddddddddddddddddddddddd
None
EventTH.W001   ERROR    2019-05-22 12:37:30,908 EventTH.EventTH.W001: Uncaught exception running job 'set_attribute_push' called from thread Dummy-1:
  File "/home/tnunez/sardana_sep2/src/sardana/tango/pool/TwoDExpChannel.py", line 263, in read_DataSource
    data_source = self.twod.get_data_source()
  File "/home/tnunez/sardana_sep2/src/sardana/pool/pooltwodexpchannel.py", line 57, in get_data_source
    self._set_data_source(data_source, propagate=propagate)
  File "/home/tnunez/sardana_sep2/src/sardana/pool/pooltwodexpchannel.py", line 68, in _set_data_source
    EventType("data_source", priority=propagate), data_source)
  File "/home/tnunez/sardana_sep2/src/sardana/sardanabase.py", line 130, in fire_event
    listeners=listeners)
  File "/home/tnunez/sardana_sep2/src/sardana/sardanaevent.py", line 110, in fire_event
    self._fire_event(event_type, event_value, listeners=listeners)
  File "/home/tnunez/sardana_sep2/src/sardana/sardanaevent.py", line 132, in _fire_event
    real_listener(self, event_type, event_value)
  File "/home/tnunez/sardana_sep2/src/sardana/tango/pool/TwoDExpChannel.py", line 95, in on_twod_changed
    self._on_twod_changed(event_source, event_type, event_value)
  File "/home/tnunez/sardana_sep2/src/sardana/tango/pool/TwoDExpChannel.py", line 151, in _on_twod_changed
    priority=priority, error=error, synch=False)
  File "/home/tnunez/sardana_sep2/src/sardana/tango/core/SardanaDevice.py", line 317, in set_attribute
    priority=priority, synch=synch)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/taurus/core/util/threadpool.py", line 135, in run
    cmd(*args, **kw)
  File "/home/tnunez/sardana_sep2/src/sardana/tango/core/SardanaDevice.py", line 329, in set_attribute_push
    error=error, priority=priority)
  File "/home/tnunez/sardana_sep2/src/sardana/tango/core/SardanaDevice.py", line 349, in _set_attribute_push
    "Cannot set value of attribute '%s' with None" % (attr_name,))
Exception: Cannot set value of attribute 'datasource' with None


Even if I see the correct value in the attribute DataSource of the 2D dummy device. i can avoid
this error if I change:

if not propagate:

to:

if not propagate or data_source == None:

in the function _set_data_source of the  Pool2DExpChannel (file pooltwodexpchannel.py)  class.

**Comment by teresanunez** [comment]
Another observartion, if I set SimulationMode in the TwoD dummy controller, the scans can still
 be performed but ct with the twod as argument stays for ever, one has to kill the macro with ctrl-C

**Comment by reszelaz** [comment]
> if I have a 2D in th MG and run ascan or ct without given an exp channel as argument, the
ValueRef is never updated with what i write in ValueRefPattern

In this case you use the measurement group acquisition. Then you need to cofigure the pattern on the measurement group level, for example, using the expconf (_Ref Pattern_ column). Do you do it like this? 

> ... but if without changing anything I run ct giving the 2D as argument, the ValueRef is updated with what is written ValueRefPattern.

The ValueRefPattern attribute is to configure the single channel acquisition.

**Comment by teresanunez** [comment]
> > if I have a 2D in th MG and run ascan or ct without given an exp channel as argument, the
> > ValueRef is never updated with what i write in ValueRefPattern
> 
> In this case you use the measurement group acquisition. Then you need to cofigure the pattern on the measurement group level, for example, using the expconf (_Ref Pattern_ column). Do you do it like this?
> 
> > ... but if without changing anything I run ct giving the 2D as argument, the ValueRef is updated with what is written ValueRefPattern.
> 
> The ValueRefPattern attribute is to configure the single channel acquisition.

Thanks, it is clear to me now.

**Comment by mrosanes** [comment]
When visualizing a dummy 2D channel with taurusdevicepanel the following error appears in the Sardana Pool:
<pre>
  File "/home/mrosanes/PycharmProjects/sardana/src/sardana/tango/core/SardanaDevice.py", line 349, in _set_attribute_push
    "Cannot set value of attribute '%s' with None" % (attr_name,))
Exception: Cannot set value of attribute 'datasource' with None
</pre>

data_source is deprecated

**Comment by reszelaz** [comment]
> When visualizing a dummy 2D channel with taurusdevicepanel the following error appears in the Sardana Pool:
> 
>   File "/home/mrosanes/PycharmProjects/sardana/src/sardana/tango/core/SardanaDevice.py", line 349, in _set_attribute_push
>     "Cannot set value of attribute '%s' with None" % (attr_name,))
> Exception: Cannot set value of attribute 'datasource' with None
> data_source is deprecated

This is the same what @teresanunez reported in https://github.com/sardana-org/sardana/pull/775#issuecomment-494749686. I'm working on it.

**Comment by reszelaz** [comment]
> This is the same what @teresanunez reported in #775 (comment). I'm working on it.

This error is already in develop branch, it is not related to SEP2. I will try to fix it anyway.

**Comment by reszelaz** [comment]
> This error is already in develop branch, it is not related to SEP2. I will try to fix it anyway.

@teresanunez I proposed #1111 and assigned the review to you. Thanks!

**Comment by reszelaz** [comment]
> Another observartion, if I set SimulationMode in the TwoD dummy controller, the scans can still
be performed but ct with the twod as argument stays for ever, one has to kill the macro with ctrl-C
I will have a look to see what does mean SimulationMode there, but in any case, it takes time to
discover why suddenly the macro ct does not work for single acquisition of the twod, so I think at
least some message should be thrown.

Sorry I couldn't test it yet. But have you tried it in develop branch? With 2D or with C/T?

**Comment by teresanunez** [comment]
> > Another observartion, if I set SimulationMode in the TwoD dummy controller, the scans can still
> > be performed but ct with the twod as argument stays for ever, one has to kill the macro with ctrl-C
> > I will have a look to see what does mean SimulationMode there, but in any case, it takes time to
> > discover why suddenly the macro ct does not work for single acquisition of the twod, so I think at
> > least some message should be thrown.
> 
> Sorry I couldn't test it yet. But have you tried it in develop branch? With 2D or with C/T?

I have tried it in SEP2 with 2D.  I will try now in the develop branch with 2D and CT and then I tell you.

**Comment by teresanunez** [comment]
> > > Another observartion, if I set SimulationMode in the TwoD dummy controller, the scans can still
> > > be performed but ct with the twod as argument stays for ever, one has to kill the macro with ctrl-C
> > > I will have a look to see what does mean SimulationMode there, but in any case, it takes time to
> > > discover why suddenly the macro ct does not work for single acquisition of the twod, so I think at
> > > least some message should be thrown.
> > 
> > 
> > Sorry I couldn't test it yet. But have you tried it in develop branch? With 2D or with C/T?
> 
> I have tried it in SEP2 with 2D. I will try now in the develop branch with 2D and CT and then I tell you.

It happens already in develop and with any timerable. I have tried not only with the dummy controllers but also with another counter/timer and it behaves in the same way.

**Comment by reszelaz** [comment]
Thanks to all for your reviewes and tests! Since all are positive I proceed with the merge and mark this SEP as accepted.

**Pull request merged**
