### PR TITLE
645 issue - Allow string ParamRepeats on load Sequencer plain text

### PR DESCRIPTION
**Pull request by droldan**
This pull request allows to use a paramrepeats macros with a new/old interface syntax when a plaintext file is loaded in a sequencer.
Also an Official sardana ParamParser is used to extract the params.
The ParamFactory has been improved to allow create all kind of parameters. (SingleParamNode, RepeatParamNode) passing macroInfo dictionary or a simple values (list or single value)

### CODE REVIEW

**Comment by mrosanes** [comment]
Hi Dani, I've reviewed the code; many of the examples of param repeats works, but many others does not. 

Some issues are present in single numbers that are not taken as a single number (e.g. 15 is taken as '1' and '5'); to nested parameters; to default values '[]' that are not taken correctly; to strings that are cut in many letters (e.g: mot10 - 'm' 'o' 't'...).

I have tested this implementation with the examples present in sardana.macroserver.macros.examples. 

Three different kind of errors are found:
1- Param Repeats that are described in the new interface, but does not work in the sequencer from plain text:
<pre>
pt3d [1 15] 
pt3d [1 [] 15]
pt6 mot1 [1 34 1]
pt12 [1 3 4] [mot1 mot2]
pt14 [[[mot1 mot2] 3] [[mot3] 5]]
pt14d [[[mot1 mot2] 3] [[mot3] []]]
pt14d [[[mot1 []] 3] [[mot3] []]]
pt14d [[[[]] 3] [[mot3] []]]
</pre>

2- Param Repeats that are described in the old interface, but does not work in the sequencer from plain text:
<pre>
pt5 mot1 1 3
</pre>

3- Does work from your implementation, but according to the new interface, it should not be accpeted, thus it should not be accepted by the sequencer:
<pre>
pt3 [[1] [15]]
</pre>


These issues should be addressed. The examples within sardana.macroserver.macros.examples can help in testing if the implementation works as expected with the old and the new interfaces.

**Comment by reszelaz** [comment]
Since according to the @mrosanes review there are still things to improve, for the moment, I will exclude it from this the Jan18 milestone. Having news from you we could reconsider it again.

**Comment by droldan** [comment]
Hi @mrosanes and @reszelaz, thanks for you review.

I have found some issues with paramrepeats empty with paramrepeats empty, the issue has been fixed and tested with the examples present in sardana.macroserver.macros.examples.

**Comment by tiagocoutinho** [comment]
Hi, what will be the resolution for this PR? Is it superseded by #781 or will it be merged?

**Comment by tiagocoutinho** [comment]
Hi @reszelaz,
Sorry I was unable to test this for the Jul19 release.

**Pull request merged**
