### PR TITLE
Release Jul17

### PR DESCRIPTION
**Pull request by reszelaz**
This is a PR to **master** for the official Jul17 release. Final tests (automatic and manual) will be done based on it before accepting the merge. At Alba we will test this relesae on Debian9, OpenSUSE11.1 and Windows7. We encourage reviews from other institutes but it is not "formally" requested. However, it would be nice that @sardana-org/integrators at least take a look at the [CHANGELOG](https://github.com/sardana-org/sardana/blob/release-Jul17/CHANGELOG.md) and express their opinion about the release. 

Note that the appveyor artifacts can be used for the manual tests.

### CODE REVIEW

**Comment by teresanunez** [comment]
HI @reszelaz, I can not really test it because of the problems with the versions that are required
 for the different packages, so we can not use this Release at DESY just now. But it is fine for me.

**Comment by teresanunez** [comment]
HI @reszelaz, I have released the taurus version request and so I can run it and make some checks.

**Comment by reszelaz** [comment]
Please wait with the tests. I have just discovered about two possible optimizations in the continuous scans (`ascnct`):
* going to the pre-start position could be done with the maximum velocity (if defined) instead of using the current velocity as it is done now
* correcting the overshoot could be done with the backup velocity (the one that was configured before the scan was executed) in case the maximum velocity is not defined instead of using the velocity of the scan 

I will develop these optimizations during this afternoon and push it directly to the release branch.

@teresanunez are the dependencies still problematic to you? The only one which changes with respect to the last releases is that it requires at least Taurus 3.7.4 (for Taurus3) and Taurus 4.1.1 (for Taurus4).

**Comment by teresanunez** [comment]
@reszelaz, I change the Taurus requirement to 3.6 and now it is fine. Thanks.

**Comment by reszelaz** [comment]
These requirements are necessary, otherwise the continuous scans (`ascanct`) and timescan won't work.
The critical commit is: https://github.com/taurus-org/taurus/commit/4c0fb26062ed1abe0cd9a75e4ad30c973ca3516e. Upgrade from Taurus 3.6.0 to 3.7.4 should be straightforward.

**Comment by reszelaz** [comment]
> Please wait with the tests. I have just discovered about two possible optimizations in the continuous scans (ascnct).

These optimizations are already implemented and pushed to the PR branch.

**Comment by amilan** [comment]
Hi all, 

I will review the changes and make some tests on CentOS 7, using the last release of Taurus.

**Comment by teresanunez** [comment]
I have now installed Taurus3.7.4, so I can also make some tests.

**Comment by reszelaz** [comment]
Thanks for your offer @amilan and @teresanunez.

During the tests on OpenSUSE 11.1 we have found the following problem #517. However, we see it as not release critical. If you have another opinion, please rise your hand.

**Comment by reszelaz** [comment]
This [guide](https://sourceforge.net/p/sardana/wiki/release-tests/) may help you. We usually do the release manual tests following it.

Of course first, we [run the sardana test suite](http://www.sardana-controls.org/en/latest/devel/howto_test/test_run_commands.html#run-tests-from-command-line)

**Comment by LJBD** [comment]
@reszelaz - Is this guide that you've mentioned a part of Sardana documentation yet? Or is it still on Sourceforge only?

**Comment by reszelaz** [comment]
The idea is to move it to the doc as it was [done in taurus](https://github.com/taurus-org/taurus/blob/develop/doc/how_to_release.md). The thing is that right now I don't have time to migrate it there so I thought it was better to share it as it is, if it helps...

**Comment by teresanunez** [comment]
Hi, I have run the testsuite and some manual tests. The manual tests have work without problems.
With the testsuite I got at the end:
---------------------------------------------------------------------
Ran 180 tests in 590.412s

OK (skipped=3, expected failures=1)

During the run I saw these errors:


test_count_2 (sardana.taurus.core.tango.sardana.test.test_pool.TestMeasurementGroup)
count with 0D ... TimerLoop 1    ERROR    2017-08-02 12:53:01,756 TaurusPollingTimer[3000]: poll_reply error
ok
test_count_3 (sardana.taurus.core.tango.sardana.test.test_pool.TestMeasurementGroup)
count with 1D ... TimerLoop 1    ERROR    2017-08-02 12:53:04,786 TaurusPollingTimer[3000]: poll_reply error
ok
test_count_4 (sardana.taurus.core.tango.sardana.test.test_pool.TestMeasurementGroup)
count with 2D ... TimerLoop 1    ERROR    2017-08-02 12:53:07,757 TaurusPollingTimer[3000]: poll_reply error
ok
test_count_5 (sardana.taurus.core.tango.sardana.test.test_pool.TestMeasurementGroup)
count with Tango attribute ... TimerLoop 1    ERROR    2017-08-02 12:53:10,762 TaurusPollingTimer[3000]: poll_reply error
ok
...
Testing recorddata(apply_interpolation=False, data={'ch1': [10.0, nan, 12.0, [nan, nan, nan], 16.0], 'ch2': [20.0, 21.0, [22.0, 23.0, 24.0], nan, [26.0]], 'ch3': [nan, nan, 32.0, 33.0, 34.0, 35.0, 36.0]}) ... HDF5-DIAG: Error detected in HDF5 (1.8.13) thread 140696015075072:
  #000: ../../../src/H5A.c line 628 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: ../../../src/H5A.c line 878 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
....


Manually I have run scans and saved the data in nexus without problems, and also open the files using showscan.

One comment, for running the interactive macros ask_peak, ask_for_moveable ... one has to add
 first the example directory to the MacroPath, if not the macros are not seen ... this can be confusing,
 I mean, one has to realize the reason why the macros are not there.

For the rest it is fine for me. I tested it in debian8, tango9, taurus3.7.4

**Comment by reszelaz** [comment]
Thanks @teresanunez for your tests!

Regarding the HDF5-DIAG: Error detected... It also happens when we run automatic tests in travis-ci, there we also use Debian 8. I assume that it is related to some "bug" in the libhdf5 that is redistributed with Debian 8. When I run tests on Debian 9 these messages are not there anymore. So I would not worry about it.

Regarding the MacroPath, it is documented in the point 4 of the paragraph: "How to create testing environment and run testsuite" in [the guide](https://sourceforge.net/p/sardana/wiki/release-tests/). But I agree that the guide is quite poor right now. We will add more details to the guide when we find time to migrate it to the docs.

**Comment by teresanunez** [comment]
HI @reszelaz, thanks for the information. Sorry, you are right ... I see it now in the point 4 ... I created
my environment without going through the points, my fault.

**Comment by amilan** [comment]
Hi again, 

I've been running some tests today (following the guide that @reszelaz suggested).

The sardanatestsuite is running OK, but I have a small comment:

I had some issues running the test suite because the tango host in my test environment is 127.0.0.1:10000, and in the test_measurementgroup.py, when getting the db_host, there is a split('.')[0] ... so you can imagine what happens in my set up.
I suppose that this is done like that in order to remove the domain from a tango host, but what I'm not sure is if having the domain in there could cause problems.
In any case, this is not so important, because in production the tango host has a proper name and not an IP, but I wanted to comment it here, just in case anyone else find the same issue. (comment or remove the split solves it).

Apart from that, I have also done some manual tests and I have a core dump when executing the macro: showscan from spock.

I have the JsonRecorder set to True, then I run an ascan and after that I try to run showscan, and I get this: 
```
Door_rel-jul17_1 [3]: %ascan mot09 0 10 4 0.1
Operation will be saved in /tmp/test.dat (Spec)
Scan #38 started at Thu Aug  3 17:19:27 2017. It will take at least 0:00:03.183282
 #Pt No    mot09      ct09      ct10      ct11      ct12       dt   
   0         0        0.1       0.2       0.3       0.4     0.922383
   1        2.5       0.1       0.2       0.3       0.4     1.53715 
   2         5        0.1       0.2       0.3       0.4     2.13392 
   3        7.5       0.1       0.2       0.3       0.4     2.73892 
   4         10       0.1       0.2       0.3       0.4     3.34663 
Operation saved in /tmp/test.dat (Spec)
Scan #38 ended at Thu Aug  3 17:19:30 2017, taking 0:00:03.475105.Dead time 85.6% (motion dead time 80.7%)

Door_rel-jul17_1 [4]: %showscan
MainThread     CRITICAL 2017-08-03 17:19:33,988 TaurusRootLogger: Qt: QWidget: Must construct a QApplication before a QPaintDevice
TaurusTP.W001  ERROR    2017-08-03 17:19:35,664 TaurusManager.TaurusTP.TaurusTP.W001: Uncaught exception running job 'run_forever' called from thread MainThread:
  File "/home/antmil/tmp/venvtest/vtest/bin/spock", line 11, in <module>
    load_entry_point('sardana==2.3.0', 'console_scripts', 'spock')()
  File "/home/antmil/tmp/venvtest/vtest/lib/python2.7/site-packages/sardana-2.3.0-py2.7.egg/sardana/spock/__init__.py", line 34, in main
    run()
  File "/home/antmil/tmp/venvtest/vtest/lib/python2.7/site-packages/sardana-2.3.0-py2.7.egg/sardana/spock/ipython_01_00/genutils.py", line 1310, in run
    prepare_input_handler()
  File "/home/antmil/tmp/venvtest/vtest/lib/python2.7/site-packages/sardana-2.3.0-py2.7.egg/sardana/spock/ipython_01_00/genutils.py", line 1221, in prepare_input_handler
    _ = sardana.spock.inputhandler.InputHandler()
  File "/usr/lib/python2.7/site-packages/taurus/core/util/singleton.py", line 79, in __new__
    cls._the_instance.init(*p, **k)
  File "/home/antmil/tmp/venvtest/vtest/lib/python2.7/site-packages/sardana-2.3.0-py2.7.egg/sardana/spock/inputhandler.py", line 116, in init
    proc.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 126, in __init__
    code = process_obj._bootstrap()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/antmil/tmp/venvtest/vtest/lib/python2.7/site-packages/sardana-2.3.0-py2.7.egg/sardana/spock/inputhandler.py", line 138, in safe_run
    return self.run(conn)
  File "/home/antmil/tmp/venvtest/vtest/lib/python2.7/site-packages/sardana-2.3.0-py2.7.egg/sardana/spock/inputhandler.py", line 152, in run
    TaurusManager().addJob(self.run_forever, None)
  File "/usr/lib/python2.7/site-packages/taurus/core/taurusmanager.py", line 129, in addJob
    self._thread_pool.add(job, callback, *args, **kw)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/taurus/core/util/threadpool.py", line 135, in run
    cmd(*args, **kw)
  File "/home/antmil/tmp/venvtest/vtest/lib/python2.7/site-packages/sardana-2.3.0-py2.7.egg/sardana/spock/inputhandler.py", line 161, in run_forever
    message = conn.recv()
EOFError
[1]    8125 abort (core dumped)  spock --profile=rel-jul17
```
Is anyone else experiencing something like that?

**Comment by reszelaz** [comment]
@amilan thanks for your tests!

> In any case, this is not so important, because in production the tango host has a proper name and not an IP, but I wanted to comment it here, just in case anyone else find the same issue. (comment or remove the split solves it).

From your description, for me, this deserves creation of a separate issue. But it does not look like release blocking.

> Apart from that, I have also done some manual tests and I have a core dump when executing the macro showscan from spock.

This also deserves a separate issue. From the traces I suspect some relation with the interactive macros. Maybe it is some consequence of the previous tests/errors run on the same system? Is it possible to reproduce it when starting the Sardana from scratch? Which OS do you use?

**Comment by teresanunez** [comment]
Hi @amilan, for me showscan works without problems. For taurus I have the code in the branch support3.x. Only one thing, showscan reads the data from the nexus file where the scan was saved
(it takes the name from the environment), in your case you are saving the data in Spec format, but
 in any case if the file is not nexus the error that I get is:

Trying to open local scan file /tmp/test.spe...
IOError: unable to open file (File accessibilty: Unable to open file)
(For more detailed information type: python_error)

But not the one you see. Have you tried saving the data in NeXus?.
@reszelaz, perhaps it is not right what I wrote ... it is what I learnt using it.

**Comment by reszelaz** [comment]
@teresanunez you are completely right. I did not realize that the h5 was not stored. But as you said there should be a different error and the spock should not crash.

**Comment by amilan** [comment]
Hi again, 

Sorry, today I didn't have too much time for testing, but regarding my two comments, the first one is not an issue at all, it's just for the convenience of running tests, but it doesn't prevent us for creating the new release.

For the second one, at the beginning I started saving the data in nexus files and I had the issue, later on I moved to spec files to make another quick test and when I wanted to report the error I just forgot to change the file format again, but it's still causing the same error. 
In any case, it looks like this is a problem in my set-up rather than in sardana, so I don't think this is a blocking issue. You can continue with the creation of the release, and on my side I will continue looking at it on Monday.

**Comment by reszelaz** [comment]
We will have to delay the release at least until the next week - we have not tested yet on Windows.
@amilan please keep us updated with results of your tests. Thanks to all!

**Comment by amilan** [comment]
Hi again, 

Today I could continue with the tests and I have found what was the cause of my problem. 
I was missing the QT4 backend for matplotlib in my set up.

I'm using centos 7, so running:
```
sudo yum install python-matplotlib-qt4
```
Solved the issue.

Cheers,
Antonio.

**Comment by mrosanes** [comment]
Thanks to all for performing the tests. At Alba we have also finished with the Windows test, and there are no release blocking issues. So we think that we can release 2.3.0 version.

During the test some issues were discovered with the new and default Nexus recorder (NXscanH5_FileRecorder). These issues are documented in [#514](https://github.com/sardana-org/sardana/issues/514) and [#517](https://github.com/sardana-org/sardana/pull/517). In case that these issues are critical they can be workaround by defining a SCAN_RECORDER_MAP and pointing the h5 extension to the old Nexus recorder (NXscan_FileRecorder).

**Pull request merged**
