### PR TITLE
Expconf popup shall not appear if Pool stops

### PR DESCRIPTION
**Pull request by mrosanes**
Load/Keep externally changed configuration popup, shall not
appear if Pool stops.

This commit fixes it.

### CODE REVIEW

**Comment by cmft** [comment]
Hola @mrosanes,
Your changes cause a flake8 error. Could you fix it?
```
src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py:128:54: W504 line break after binary operator
    if bool(first) and ("MntGrpConfigs" not in first or
```

**Comment by mrosanes** [comment]
Flake8 error fixed

**Comment by reszelaz** [comment]
In this [branch](https://github.com/reszelaz/sardana/tree/expconf-print-events) we put debug traces that helps to track how originates the `QDoor.experimentConfigurationChanged` signal. Also in the same branch is implemented Option 2 explained in the above comment.

**Comment by reszelaz** [comment]
I close this one cause #1101 try to provide a better solution.

**Pull request closed without merging**
