### PR TITLE
Adapting to four circle diffractometers

### PR DESCRIPTION
**Pull request by teresanunez**
Some macros were not suited for four circle diffractometers. I have adapted them. They are now
 been in use in one of our beamlines with a E4CH diffractometer.

### CODE REVIEW

**Comment by cpascual** [comment]
Hi @teresanunez , it looks like you are the [first victim](https://travis-ci.org/sardana-org/sardana/builds/233526314#L1659) of the [new PEP8 Taliban Robot](#450)...  ;)

**Comment by teresanunez** [comment]
Sorry, I don't know why it has failed now ... is there any automatic way of correcting this?, I am getting crazy.

**Comment by reszelaz** [comment]
The errors are only W291 and W293 (whitespace). It is very easy to spot them in the GitHub PR "changes" tab. These are whitespace changes that are highlighted a little bit more dark than the other. You should eliminate them. `autopep8` would also serve for that.

**Comment by teresanunez** [comment]
I made it now with autopep8 and I put the code even in a worse state ... I think I leave it like this for now, I can not continue with this.

**Pull request closed without merging**
