### PR TITLE
Hotfix 2.2.2

### PR DESCRIPTION
**Pull request by reszelaz**
Note for @sardana-org/integrators, after merging into master, it will require also making an annotated tag: `2.2.2`. Afterwards I will make a new PR to develop with the bumped version number to `2.2.3-alhpa`.

### CODE REVIEW

**Comment by reszelaz** [comment]
travis-ci fails because the configuration file in master is not adopted to setuptools yet.
I could cherry-pick 2806f23, 363cf1b and 915f0bf from the develop branch in order to fix it also for master. What do you think?

**Comment by teresanunez** [comment]
Hi Zibi, should I proceed to the review and merge or do you prefer to wait for more
 opinions about adapting or not the configuration file?. In my opinion it could be
 merged like it is now.

**Comment by teresanunez** [comment]
The issue with the travis check is actually solved. I proceed with the merge.

**Comment by teresanunez** [comment]
The tag 2.2.2 in the master branch is also created.

**Comment by reszelaz** [comment]
Thanks @teresanunez for the integration!
I have also pushed the hotfix to develop and also bumped the version number to 2.2.3-alpha.

**Pull request merged**
