### PR TITLE
Improve exception handing in continuous scans

### PR DESCRIPTION
**Pull request by reszelaz**
Currently, StopException is not raised again to the higher layers. Due to that
the GScan.step_scan method is not able to determine if the scan was stopped
by the user or not. Furthermore, if the scan was run inside of another macro
the StopException is not propagated to the wrapper macro. Change it and
re-raise the StopException

Apart of that, after ScanException the on_waypoints_end method is not called. This
method does the necessary cleanup. Call it.

### CODE REVIEW

**Comment by reszelaz** [comment]
Thinking more about this, IMHO the `ScanException("error while moving to waypoints")` does not add more information to the end user than the original exception message. So I would go even further and re-raise the original exception. For example, in case of the measurement group CORBA timeout, we would get the following behavior:
```
Door_zreszela_1 [2]: ascanct mot01 0 1 10 0.1
ScanDir is not defined. This operation will not be stored persistently. Use Use "expconf" (or "senv ScanDir <abs directory>") to enable it
Scan #10 started at Mon Sep 25 11:08:36 2017. It will take at least 0:00:00
 #Pt No    mot01      ct01      ct02      ct03      ct04       dt   
Motor positions and relative timestamp (dt) columns contains theoretical values
Scan #10 ended at Mon Sep 25 11:08:40 2017, taking 0:00:04.001411. Dead time 100.0% (motion dead time 0.0%)
An error occurred while running Macro 'ascanct(mot01, 0.0, 1.0, 10, 0.1, 0.0) -> 1cd143e0-a1d1-11e7-9924-f8b156a48f79':
TRANSIENT CORBA system exception: TRANSIENT_CallTimedout
```
And then user can ask for more information using the `www` magic command:
```
Door_zreszela_1 [3]: www
Traceback (most recent call last):
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/msmacromanager.py", line 1277, in runMacro
    for step in macro_obj.exec_():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/macro.py", line 2276, in exec_
    for i in it:
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/macros/scan.py", line 281, in run
    for step in self._gScan.step_scan():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 892, in step_scan
    for i in self.scan_loop():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 2236, in scan_loop
    self.go_through_waypoints()
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 1206, in go_through_waypoints
    self._go_through_waypoints()
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 2166, in _go_through_waypoints
    mg_id = self.measurement_group.start()
  File "/home/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 260, in new_fn
    return fn(*args, **kwargs)
  File "/home/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 437, in start
    self._start(*args, **kwargs)
  File "/home/zreszela/workspace/sardana/src/sardana/taurus/core/tango/sardana/pool.py", line 1720, in _start
    self.Start()
  File "/usr/lib/python2.7/dist-packages/tango/device_proxy.py", line 218, in f
    return dp.command_inout(name, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/tango/green.py", line 266, in greener
    ret = submitter(fn, self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tango/green.py", line 100, in submit
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tango/connection.py", line 101, in __Connection__command_inout
    r = Connection.command_inout_raw(self, name, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/tango/connection.py", line 127, in __Connection__command_inout_raw
    return self.__command_inout(cmd_name, param)
CommunicationFailed: DevFailed[
DevError[
    desc = TRANSIENT CORBA system exception: TRANSIENT_CallTimedout
  origin = Connection::command_inout()
  reason = API_CorbaException
severity = ERR]

DevError[
    desc = Timeout (3000 mS) exceeded on device mntgrp/pool_zreszela_1/mntgrp01, command Start
  origin = Connection::command_inout()
  reason = API_DeviceTimedOut
severity = ERR]
]
```
Instead of the current behavior:
```
Door_zreszela_1 [2]: www
Traceback (most recent call last):
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/msmacromanager.py", line 1277, in runMacro
    for step in macro_obj.exec_():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/macro.py", line 2276, in exec_
    for i in it:
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/macros/scan.py", line 281, in run
    for step in self._gScan.step_scan():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 892, in step_scan
    for i in self.scan_loop():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 2245, in scan_loop
    self.go_through_waypoints()
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 1217, in go_through_waypoints
    raise ScanException('error while moving to waypoints')
ScanException: error while moving to waypoints
```
And useless output of `www`:
```
Door_zreszela_1 [2]: www
Traceback (most recent call last):
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/msmacromanager.py", line 1277, in runMacro
    for step in macro_obj.exec_():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/macro.py", line 2276, in exec_
    for i in it:
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/macros/scan.py", line 281, in run
    for step in self._gScan.step_scan():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 892, in step_scan
    for i in self.scan_loop():
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 2245, in scan_loop
    self.go_through_waypoints()
  File "/home/zreszela/workspace/sardana/src/sardana/macroserver/scan/gscan.py", line 1217, in go_through_waypoints
    raise ScanException('error while moving to waypoints')
ScanException: error while moving to waypoints
```
I will add the necessary commit right now.

**Comment by teresanunez** [comment]
Hi @reszelaz, I completely agree with this change. In fact during my tests I have always modified the file for not getting the 'error while moving to waypoints' error but a real one ... if not it is really difficult to know
what is going on.

**Comment by reszelaz** [comment]
Great! Let's hope this will improve the user experience.

**Comment by droldan** [comment]
Nice!! It helps us a lot not to hide the source of the problem., this will improve the user experience and our debugging experience!
Thanks!

**Comment by reszelaz** [comment]
With the agreemend of @teresanunez and @droldan I proceed with the merge.

**Pull request merged**
