### PR TITLE
Adding diffractometer types

### PR DESCRIPTION
**Pull request by teresanunez**
This PR adapt the hkl controller for accepting two new diffractometer types.

### CODE REVIEW

**Comment by teresanunez** [comment]
It is already being use in one of our beamlines that requires these new types.

**Comment by cmft** [comment]
Hi @teresanunez ,
There are some PEP8 warning. Fixing them I believe that this PR could be integrated

```
src/sardana/pool/poolcontrollers/HklPseudoMotorController.py:1415:80: E501 line too long (108 > 79 characters)
    pseudo_motor_roles = "h", "k", "l", "psi", "q", "alpha", "tth2",  "alpha_tth2", "incidence", "emergence"
                                                                               ^
src/sardana/pool/poolcontrollers/HklPseudoMotorController.py:1459:1: E302 expected 2 blank lines, found 1
class Diffrac4Cp23(DiffracBasis):  # DiffractometerType: "PETRA3 P23 4C"
^
src/sardana/pool/poolcontrollers/HklPseudoMotorController.py:1463:80: E501 line too long (116 > 79 characters)
    pseudo_motor_roles = "h", "k", "l", "q", "alpha", "qper", "qpar", "tth2", "alpha_tth2", "incidence", "emergence"
```

**Comment by teresanunez** [comment]
Hi @cmft, many thanks for looking at that. I have now corrected the pep8 errors.

**Comment by reszelaz** [comment]
Thanks @teresanunez for the PR and @cmft for the review. I see it fine to integrate so I proceed with merging.


At some point we could think of eliminating the `#noqa` and formatting the comments, code to fit withing 79 columns.
I don't know if `@param` in the docstring is compatible with restructuredtext? At least it is not the style that we use in Sardana. So I propose to change it as well to `:param`.

**Pull request merged**
