### PR TITLE
Fix bug when updating macro arguments

### PR DESCRIPTION
**Pull request by jordiandreu**
A string value is expected as argument for updateMacroArgument
method. However, this value comes from any valid signal and
could be any other object.

Remove the regular expression statement before string conversion.

### CODE REVIEW

**Comment by reszelaz** [comment]
Thanks for your contribution! I have some comments...

We need to keep the conditional encapsulation of the string parameters within quotes in order to be compatible with parameters that contain spaces. It was introduced in b49f62eb3 

What I suggest is to relax the `updateMacroArgument` API to accept arguments of other types than `str` and convert these values with `Qt.from_qvariant`.

Please check my proposal and feedback.

**Comment by cpascual** [comment]
> What I suggest is to relax the updateMacroArgument API to accept arguments of other types than str and convert these values with Qt.from_qvariant.

Do not use Qt.from_qvariant. It is not a standard method and provided only [for backwards compatibility](http://pyqt.sourceforge.net/Docs/PyQt5/pyqt_qvariant.html). Better use standard python casting

**Comment by reszelaz** [comment]
Thanks! I have already changed the code. @jordiandreu please check it now.

**Comment by jordiandreu** [comment]
I have already checked the code proposed by @reszelaz and it works fine. So, in my opinion you can go ahead.

**Comment by reszelaz** [comment]
Thanks for the feedback. I've just merged it.

**Pull request merged**
