### PR TITLE
Release jul20

### PR DESCRIPTION
**Pull request by aureocarneiro**
This is a PR to master for the official [Jul20 release](https://github.com/sardana-org/sardana/milestone/7). Final tests (automatic and manual) should be done based on it before accepting the merge.

So, this is a call for help from @sardana-org/integrators and any other person willing to help to test this branch ASAP in their respective systems.

For the moment the following systems are going to be tested thoroughly (feel free to add more to the list if you are willing to do the tests):

- [x] Debian 9 (#1392)
- [x] CentOS 7 (#1393)
- [x] Windows 10 (#1391)

### CODE REVIEW

**Comment by reszelaz** [comment]
Many thanks @aureocarneiro!

Some additional infos:

* the [appveoyor artifacts](https://ci.appveyor.com/project/taurusorg/sardana/builds/34817431) can be used for the tests.

* the tests will be done with [taurus 4.7.0](https://github.com/taurus-org/taurus/releases/tag/4.7.0).

* I have also [updated](https://github.com/reszelaz/sardana-test/commit/515586509ca0aff2c1948a015bbab7eba8907103) the sardana-test Docker image to use taurus 4.7. As soon as the image is ready on docker hub I will restart the travis-CI jobs of this PR to validate that the testsuite still works correctly.

**Review by reszelaz — APPROVED** [review]
For me everything looks OK.
There are conflicting files. I think this could be solved when locally merging release-Jul20 into the master branch. @aureocarneiro fo you want me to do it?

**Comment by aureocarneiro** [comment]
> For me everything looks OK.
> There are conflicting files. I think this could be solved when locally merging release-Jul20 into the master branch. @aureocarneiro fo you want me to do it?

I can do it :)

**Comment by aureocarneiro** [comment]
@sardana-org/integrators please review it :)

**Comment by reszelaz** [comment]
@teresanunez and @cpt-majkel could you please review and eventually approve the release. Many thanks!

**Review by teresanunez — APPROVED** [review]

**Review by cpt-majkel — APPROVED** [review]

**Pull request merged**
