### PR TITLE
Print multiple macro results in spock - fix #366

### LINKED ISSUE #366: Spock shows only one returned value (SF#522)
If a macro returns more than one value spock shows only one value (the first one)

I attached a macro example:

<pre>
from sardana.macroserver.macro import Macro, macro, Type

class ret2parms(Macro):

    result_def = [
       ['v1', Type.Integer, None, 'Value 1'],
       ['v2', Type.Integer, None, 'Value 2']
    ]

    def run(self, *args):
        return 1, 2
</pre>

And the spock output:

<pre>
Door_cfalcon_1 [3]: %ret2parms
[START] runMacro Macro 'ret2parms() -> de60f03e-a103-11e6-809c-f8b156a85fef'
sending result ['1', '2']
[ END ] runMacro Macro 'ret2parms() -> de60f03e-a103-11e6-809c-f8b156a85fef'
Job ended (stopped=False, aborted=False)
        Result [3]: 1
</pre>
    

Reported by: cmft ( http://sf.net/u/cmft )

Original Ticket: [sardana/tickets/522](https://sourceforge.net/p/sardana/tickets/522)

### PR DESCRIPTION
**Pull request by reszelaz**
This PR fixes #366. I did not find a way to print multiple outputs with a line magic in IPython. So multiple results are encapsulated in a tuple and printed on one output.

@cmft could you check if it works for you now and feedback.

### CODE REVIEW

**Comment by cmft** [comment]
Hi @reszelaz,
The PR fix the bug.

Thanks

**Comment by reszelaz** [comment]
Thanks! I'm merging it.

**Comment by cmft** [comment]
Sorry. I did more test and I found an error. If a macro can not be executed the output of the previous macro  is showed.

See:
```
Door_cfalcon_1 [4]: %ret2parms

Door_cfalcon_1 [5]: %ret2parms
        Result [5]: (1, 2)

Door_cfalcon_1 [6]: ct
        Result [6]: (1, 2)

Door_cfalcon_1 [7]: ct 1
Error: The macro ct requires the following missing environment to be defined: ['ActiveMntGrp']
        Result [7]: (1, 2)
```

**Comment by reszelaz** [comment]
This bug already existed before integrating this PR and is reported as #502

**Pull request merged**
