### PR TITLE
Add option for node duplication in macroexecutor (issue 426)

### PR DESCRIPTION
**Pull request by sagiss**
Add option for node duplication in macroexecutor (issue 426).
Add button in macroexecutor for allowing RepeatNode duplication.

### CODE REVIEW

**Comment by sagiss** [comment]
Tests Ok:
- Tested with macros generic 'wm' and 'mv'.
- Tested with 'manytomos' specific macro from beamline scientists.

**Comment by sagiss** [comment]
After testing sequencer it presented failures. The nodes where not duplicated till clicking on the button for adding nodes. Then a refresh of the view was done. 

I will propose changes in the code.

**Comment by sagiss** [comment]
Review: The icon gtk-copy is not visible using sequencer with taurus3.  Fix it.

**Comment by cpascual** [comment]
Oooops!! 
Sorry, I wanted to push just the last commit (a6a9859), but I pushed also all the changes in develop since you branched. 
Anyway, that is not beautiful, but neither harmful... Just ignore from a08bd50 till c3ccf03 if you are reviewing

**Comment by cpascual** [comment]
The feature seems to work fine using Taurus4, both for macroexecutor and for the sequenceeditor, **but** I found the following issues:

- It did not work (the duplicate button did not appear) when run in a Suse12 (PyQt4.4, taurus3,...) neither in  macroexecutor nor in the sequenceeditor.
- I expected (maybe unjustifiably?)  that I would be able to duplicate whole macro nodes in the sequencer just as one can duplicate a param repeat node... but that is not the case.
- The copy button (at  least in my system) changes very little when it is disabled (it makes it difficult to tell if the action is enabled or disabled)

Of the three, only the first seems important to me, and if it is difficult to implement, I would agree tomerge this PR and open a bug for porting it to older libs.

**Pull request merged**
