### PR TITLE
Optional param

### PR DESCRIPTION
**Pull request by rhomspuron**
Implement optional parameter for the macros. Adds #285.

### CODE REVIEW

**Comment by rhomspuron** [comment]
Hi @dschick, thanks for test it!!! 

I just tested with the next code:
```python
class ch(Macro):
    param_def = [['ch', Type.ExpChannel, OptionalParam, 'name of counter']]

    def run(self, ch):
        if ch is OptionalParam:
            ch = self.getExpChannel('ct29')
        self.info(ch)
``` 
And it worked. Output:
```python
Door_rhoms_1 [4]: ch
ct29

Door_rhoms_1 [5]: ch ct30
ct30
```

Could you send your macro?

**Comment by dschick** [comment]
works like a charm, my if statement was wrong like
`if counter:`
instead of
`if counter is OptionalParam`

Thanks so much

Daniel

**Comment by rhomspuron** [comment]
Hi @dschick 

After seeing your code, we think it's more intuitive and pythonic to pass a None instead of OptionalParam. I will change the code.

**Comment by dschick** [comment]
gracias! I guess this is more convinent

**Pull request merged**
