### PR TITLE
Dump info on channels if MG acq fails in step scan, ct and uct 

### PR DESCRIPTION
**Pull request by reszelaz**
MeasurementGroup may get into the FAULT state mainly due to these three reasons:
* software synchronized acquisition startup (load or start sequence) fails  
* one of its channels reports FAULT state
* the last readout of State or Value/ValueRef fails.

This is only reported to the user with the exception message: `Exception: Measurement group ended acquisition with Fault state`.

Similarly to dumping information about moveables when motion fails also dump it for channels in the case the measurement group acquisition fails. 

This is something what we discussed on the last follow-up meeting based on a poor experience when debugging a problem at DESY. I think this PR adds more verbosity about the measurement group problems. For example, now we would get:

```
Door_zreszela_1 [17]: ascan mot01 0 1 1 0.001
Operation will be saved in /tmp/test.h5 (HDF5::NXscan from NXscanH5_FileRecorder)
Scan #175 started at Fri Mar 13 23:00:05 2020. It will take at least 0:00:02.830427
 #Pt No    mot01      ct01     twod01      dt
Report: Stopped at step #0 with:
ct01:
       State: Fault
      Status: ct01 is Fault
              Exception: ERROR STATE
twod01:
       State: Moving
      Status: twod01 is On
              Stopped
Operation saved in /tmp/test.h5 (HDF5::NXscan)
Scan #175 ended at Fri Mar 13 23:00:06 2020, taking 0:00:00.262264. Dead time 100.0% (motion dead time 10.0%)
An error occurred while running ascan:
Exception: Measurement group ended acquisition with Fault state
Hint: in Spock execute `www`to get more details

```
Note that there are still things to improve. For example, the channel's Status could correspond to the last readout done by the acquisition action. Now it is not the case. The Status information is read via Tango when composing the information, so an extra `StateOne` call is performed.

@teresanunez it would be great if you could review and test it. Thanks!

### CODE REVIEW

**Comment by jkotan** [comment]
Thanks @reszelaz  for PR. Is it true when you dump information about an element  its state is read second time in `PoolElement._information()`? 
If so when the first read of State is FAULT and second one is ON then you do not get the proper information.

**Comment by teresanunez** [comment]
HI Zibi, thanks. I am afraid I can not reproduce the problem we had at the beamline in order
 to test it. What I think is that both states should be shown: the one read by the MG and being
 the cause of setting the MG to fault state, and the one that is composed afterwards by infomation(). I am afraid they are often different in the difficult cases where one can not find
the reason of the FAULT state.

**Comment by reszelaz** [comment]
Yes, I agree with both of you.

Then we would need to listen to the Status events (as we now listen to the State events) on the MacroServer and then extract the Status information from the cache. When implementing this feature I already tried it and it worked. If you agree I will submit another commit with this change.

Then I think it is enough to dump just the Status from the last event and if one wants to get the new one (read again from the hardware) would need to execute: `<channel>.State()` or `<channel>.Status()`. What do you think?

**Comment by teresanunez** [comment]
Hi Zibi, thanks, for me it is fine what you propose.

**Comment by reszelaz** [comment]
> Is it true when you dump information about an element its state is read second time in `PoolElement._information()`?
> If so when the first read of State is FAULT and second one is ON then you do not get the proper information.

Sorry, in my earlier reply I had not exactly answered your question. The state won't be read unless the event is older than 3 s. I think usually it won't be, but it is safer to use the event value regardless of its timestamp. I proposed https://github.com/taurus-org/taurus/pull/1105 to make it possible.

Then as we discussed with Teresa on the previous follow-up meeting you are actually interested in the State and not in the Status so much. In this case, for the moment, I would not add listener to the Status attribute and make the extra status readout even if the status won't correspond to the one from the acquisition action. Of course printing the corresponding note to the user.

There is also one more detail. When dumping the information not all the element state events may already arrive. This is because the first element in the measurement group reporting the Fault state is already changing the measurement group state to Fault and this lets the scan proceed with the information dump. The events from the remaining elements may arrive later. This may cause situation like the one from the PR description - ct01 - Fault but twod01 - Moving. I will check tomorrow if I can make it work better without too much effort.

**Comment by reszelaz** [comment]
> When dumping the information not all the element state events may already arrive. This is because the first element in the measurement group reporting the Fault state is already changing the measurement group state to Fault and this lets the scan proceed with the information dump. The events from the remaining elements may arrive later. This may cause situation like the one from the PR description - ct01 - Fault but twod01 - Moving.

I have investigated this a little and I don't have it very clear if we want to change the current behavior - whenever there is one element in Fault the whole measurement group goes into the Fault. The same is with the Alarm. For example the _emergency stop_ feature in the case of a multiple elments move is based on that. And I think the emergency stop feature also makes sense for the measurement group. This I think would be a solution to #792. So, I propose to docouple this two issues: dumping info and emergency stop.

Then I have added the timestamp information to the dumped state and status and the information looks like this now:

```
Door_zreszela_1 [1]: ct
Fri May 08 16:09:38 2020

Elements ended acquisition with:
ct01:
       State: Fault (16:09:39.558505)
      Status: ct01 is Fault
              Exception: Communication error (16:09:39.573659)
zerod01:
       State: On (16:09:39.571555)
      Status: zerod01 is On
              OK (16:09:39.573874)
An error occurred while running ct:
Exception: Measurement group ended acquisition with Fault state
Hint: in Spock execute `www`to get more details
```
Then I'm merging it as it is and whenever https://github.com/taurus-org/taurus/pull/1105 gets accepted into Taurus we will use this feature to ensure that the state information comes from cache even if it is older than 3 s.

**Pull request merged**
