### PR TITLE
Present Pool Servers by alphabetical order

### PR DESCRIPTION
**Pull request by mrosanes**
When creating a MacroServer, the Pool names are presented in
order to allow the user to choose one of them.

Present them by alphabetical order.

### CODE REVIEW

**Comment by mrosanes** [comment]
This pull request, should solve issue https://github.com/sardana-org/sardana/issues/585

**Comment by teresanunez** [comment]
Hi, I have checked it and it solves both issues presented in #585. In my opinion it could be merged.
I don't know if somebody else want to review it ( @reszelaz  ?), if not I could merge it.

**Comment by reszelaz** [comment]
@teresanunez thanks for reviewing it! I have also checked it and the changes in the while loop made that it is not possible to connect to more than one Pool. @mrosanes could you come back to the previous behavior?

**Comment by teresanunez** [comment]
Hi @reszelaz, yes, I realized about that, but I thought that it was your decission to change that (allowing
 connecting to only one Pool), I remeber to read about that in some comments.

**Comment by mrosanes** [comment]
In fact, the question of being able to choosing a Pool being presented more than once was a feature (not a bug). Reallowed connection to more than one Pool. Added information during the process of choosing the Pools to which a given MacroServer is connected.

**Comment by teresanunez** [comment]
Hi, I have checked this again ... One point that could discussed: after selecting one pool the list of available Pools is shown again, complete, also with the already selected pool(s), it a bit confusing or even too much if the list is too long ... one can lose the overview of the pools that are already added.
Perhaps one could avoid to show again the list or, if shown, exclude the already selected. Well, it is only an opinion.

**Comment by mrosanes** [comment]
Yes, you have reason; it is too much information. We will keep the previous behavior and only print the Pool names once. I have done a new commit to deal with it.

**Comment by teresanunez** [comment]
Hi @mrosanes, thanks for the change. It is ok for me. Sorry, only as comment, for me it can
 stay like it is: perhaps it is a bit confusing to repeat the message:

 'If you wish to connect to more than one Pool,'

every time you get the possibility to connect to a new Pool ... in fact only the first time
would be 'more than one' ... But, well, it is fine.

**Comment by teresanunez** [comment]
Hi @mrosanes, thanks, for me it is fine now. I can merge it if nobody has anything against.

**Comment by reszelaz** [comment]
It looks nice now. Thanks to both!

**Pull request merged**
