### PR TITLE
Add filter for environmentChanged QDoor signals, only for experiment env config.

### PR DESCRIPTION
**Pull request by droldan**
Added a filter for _experimentConfigurationChanged_ signals with _environmentChanged_ signals as source.

Only changes to the following environment will raise an '_experimentConfigurationChanged_' QDoor signal:

- '_ActiveMntGrp_'
- '_ScanDir_'
- '_ScanFile_'
- '_DataCompressionRank_'

### CODE REVIEW

**Comment by reszelaz** [comment]
Thanks @droldan!

Maybe `PreScanSnapshot` should be included as well? `expconf` visualizes and allows to edit it.

From the [Environment Variables Catalogue](https://sardana-controls.org/users/environment_variable_catalog.html) I would also think that `ApplyInterpolation`, `ApplyExtrapolation`, `SampleInfo`, `ScanRecorder`, `SharedMemory` and `SourceInfo` are related to the *Experiment Configuration* but since for the moment expconf does not allow to edit them I would just filter them out as any other environment variable.

**Comment by droldan** [comment]
Nice @reszelaz ,
I have Included  `PreScanSnapshot` as allowed environment change events.

Thanks

**Comment by reszelaz** [comment]
Thanks @droldan. I made some refactoring. Could you re-check that it works as expected?

**Comment by droldan** [comment]
Thanks to you @reszelaz, 
Yes, I tested and it works as expected.

**Comment by reszelaz** [comment]
Great, merging then.
Now, the expconf warns about the changes only when these 5 environment variables change.

**Pull request merged**
