### PR TITLE
Do not serialize instrument information

### PR DESCRIPTION
**Pull request by cmft**
The PoolElement serialize method include instrument information,
the instrument are dynamically created and the serialization
in the PoolElement causes troubles.

Avoid to pass it.

### CODE REVIEW

**Comment by reszelaz** [comment]
I agree with this change. Instrument is a dynamic property of the pool element and it can be already accessed with the Instrument attribute. So I think it does not need to be serialized - the static properties should be serialized like for example: controlle, axis, etc.

I've tested it and I have an impression that it fixes #122 but maybe @teresanunez as the original requestor could also confirm that, please?

**Comment by teresanunez** [comment]
Hi @reszelaz, no problem, I will check it as soon as possible.

**Comment by teresanunez** [comment]
The issue #122 is not solved, the problem is still there.

**Comment by reszelaz** [comment]
@teresanunez could you please describe the behavior that you observe? What I did is:

1. Start Pool and MacroServer.
2. Defined two instruments in the Pool:
Pool_zreszela_1.CreateInstrument(["/OH", "OpticalHutch"])
Pool_zreszela_1.CreateInstrument(["/OH/DCM", "DoubleCrystalMonochromator"])
3. Set Instrument to one of the motors e.g. mot01.Instrument = "/OH/DCM" 
4. I have created a taurus gui that populates panels with information from the Pool. And it correctly created the /OH/DCM panel.
5. Run a scan and save it in H5 recorder and it correctly created the link.

Everything without restarting the servers.

Btw. I don't know how to remove an element from the instrument. Do you know how to do it? If it is not possible we should create another issue for that.

**Comment by teresanunez** [comment]
I have just now tried it again. If you set an instrument to a motor it works (what you describe works also for me) but if I add an instrument to a counter the behaviour is still like described in #122.
The versionin develop works neither for counter nor for motors. Could you try with counters to confirm it?, the behaviour should be the same, shouldn't it?.
I have also tried to remove elements from an Instrument, or to delete a complete Instrument and I have not found any way to do it. I can create an issue for that.

**Comment by teresanunez** [comment]
Sorry, Instruments can be removed with DeleteElement if they do not have any element. So what is missed is how to remove elements from Intruments.

**Comment by cmft** [comment]
@teresanunez I will have  a look to the counter timer problems

**Comment by cmft** [comment]
Hola @teresanunez ,
I tested the instrument panels with a counter timer and  it works;  @reszelaz  and me  found and fix the problem with the recorder (he  will commit a path).

We  also found  visualization problems with the ct widget with taurus 4 but I will open and other issue.

**Comment by teresanunez** [comment]
Hi, I have tested it now and the issue #122 is now solved. Many thanks.

**Comment by reszelaz** [comment]
There is still one test that fails on travis:
```
======================================================================
FAIL: test_meas (sardana.macroserver.macros.test.test_expert.MeasTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sardana-2.3.3_alpha-py2.7.egg/sardana/macroserver/macros/test/test_expert.py", line 85, in test_meas
    raise e
AssertionError: Macro defmeas did not finish; State history=[u'start', u'exception']
```
I can not reproduce this fail if I run testsuite localy on a docker container.
I will need to push some commits with debug lines in order to understand better what is going on. Later on I will propose another PR without this commits.

**Comment by reszelaz** [comment]
The error during the `defmeas` macro is:

("[START] runMacro Macro 'defmeas(unittestmntgrp01, ['ct04', 'ct02']) -> -41'",), ('Sending exception event',), ('[ENDEX] (MacroServerException) runMacro defmeas',), ('Traceback (most recent call last):', '  File "/usr/local/lib/python2.7/dist-packages/sardana-2.3.3_alpha-py2.7.egg/sardana/macroserver/msmacromanager.py", line 1277, in runMacro', '    for step in macro_obj.exec_():', '  File "/usr/local/lib/python2.7/dist-packages/sardana-2.3.3_alpha-py2.7.egg/sardana/macroserver/macro.py", line 2270, in exec_', '    res = self.run(*self._in_pars)', '  File "/usr/local/lib/python2.7/dist-packages/sardana-2.3.3_alpha-py2.7.egg/sardana/macroserver/macros/expert.py", line 88, in run', '    pool = channel0.getPoolObj()', '  File "/usr/local/lib/python2.7/dist-packages/sardana-2.3.3_alpha-py2.7.egg/sardana/taurus/core/tango/sardana/pool.py", line 395, in getPoolObj', '    return self._pool_obj', '  File "/usr/local/lib/python2.7/dist-packages/taurus/core/taurusdevice.py", line 77, in __getattr__', '    return getattr(self._deviceObj, name)', '  File "/usr/lib/python2.7/dist-packages/PyTango/device_proxy.py", line 211, in __DeviceProxy__getattr', '    raise AttributeError(name)', 'AttributeError: _pool_obj', ''), ("An error occurred while running Macro 'defmeas(unittestmntgrp01, ['ct04', 'ct02']) -> -41':", '_pool_obj'), ('Job ended (stopped=False, aborted=False)',)

I think that the failing test is facing #57 and is not related to this PR. Execution of the same testsuite in the same docker container locally does not fail. So I propose to accept this PR, since @teresanunez already confirmed that #122 gets solved I will just propose a new PR without the dubug commits and if there are no negative opinions I will merge it tomorrow.

**Comment by reszelaz** [comment]
PR #619 was integrated in develop. Closing this PR.

**Pull request closed without merging**
