### PR TITLE
Fix #368: use setuptools instead of distutils

### LINKED ISSUE #368: Use setuptools instead of distutils (SF#524)
setup.py is currently implemented using distutils and it is heavily customized in order to provide features that could more [easily be provided](https://setuptools.readthedocs.io/en/latest/setuptools.html) if we used setuptools.

setuptools is now the [recommended solution](https://python-packaging-user-guide.readthedocs.org/en/latest/current/) for distributing python packages.

The mainatanability of sardana would improve if rewrote from scratch the setup.py file using setuptools

The bug [#506] would probably get solved with the exe scripts provided by setuptools for lauchers. 

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/524](https://sourceforge.net/p/sardana/tickets/524)

### PR DESCRIPTION
**Pull request by reszelaz**
Reimplement the whole setup.py in order to use setuptools.

Use setuptools "entry points" in order to generate scripts
on installation. This means that the script won't be available
right after cloning the repo.

Change the project maintainer to Sardana Community.

### CODE REVIEW

**Comment by reszelaz** [comment]
Tests fails due to the missing scripts (Pool & MacroServer). This has to be solved on the sardana-test container level.  I will propose it soon.

**Comment by sagiss** [comment]
Tested build documentation and tested sardana testsuite using setuptools.
Tests Suite in Sardana allows now to filter out some tests, and allow execution using setuptools. 

This pull requests fix some problems making available in sardana the commands:

python setup.py build_sphinx  (for building documentation)  
python setup.py test  (for executing tests)

Documentation on how to execute tests from command line is also updated in this pull request.

**Comment by reszelaz** [comment]
Can some of you @sardana-org/integrators review and integrate it?

**Comment by cpascual** [comment]
I reviewed the code changes and did some further tests on setuptools commands:

- test
- sdist
- bdist_wheel
- develop

It all seemed ok, so, considering also the report from @sagiss , I proceed to merge

**Pull request merged**
