### PR TITLE
Fix Door method read_ElementList

### PR DESCRIPTION
**Pull request by mrosanes**
Get the MacroServer elements when executing the Door method
read_ElementList.

### CODE REVIEW

**Comment by mrosanes** [comment]
This pull request deals with issue https://github.com/sardana-org/sardana/pull/557

**Comment by reszelaz** [comment]
Thanks for this contribution, but I would change a little bit the strategy. XXXList attributes are more oriented to exposing the user friendly information in form of strings, see Pool's InstrumentList or MotorList. The Elements attributes are foreseen for exposing all elements to the clients in form of encoded stream of data e.g. Pool's elements, MacroServer elements. I propose to eliminate this attribute at the Door level since we already have it on the MacroServer level.   Any other opinions?

**Comment by cmft** [comment]
IMO clean up the API and  avoid  multiples way to do the same thing  is  better. So, I will remove it.

I created a PR #653 to do that.

**Comment by reszelaz** [comment]
#653 removes this attribute. Closing this PR.

**Pull request closed without merging**
