### PR TITLE
Use magnitude of attributes values in PMTV

### PR DESCRIPTION
**Pull request by reszelaz**
PMTV is not ready to work with quantities and #1206 while removing
deprecation warnings introduced the use of quantities. Extract quantity
magnitude so the widget works as previously.

### CODE REVIEW

**Comment by cpascual** [comment]
I am aware of time/resource constraints and such, but... wouldn't this be a good time for making PMTV quantity-aware?
:angel: :sweat_smile:

**Comment by reszelaz** [comment]
Yes, this is a good point. However currently the PMTV (relative move) is broken when you use units. I would treat it in a separate feature (and the priority would need to compete with other issues in the backlog).

**Comment by teresanunez** [comment]
Hi Zibi, thanks, IMO it could be merged.

**Comment by reszelaz** [comment]
Thanks for the review Teresa! Merging then..

**Comment by reszelaz** [comment]
There were some bugs in this PR. I just corrected them and pushed directly to the develop branch: f0eb792e

**Pull request merged**
