### PR TITLE
Warn when macros gets overridden

### PR DESCRIPTION
**Pull request by cmft**
Add API in the server to identify if a macro is overwritten and report
a debug message.

Modify 'lsmac' macro to show if a macro has been overwritten.

Develop #930

### CODE REVIEW

**Comment by teresanunez** [comment]
I have tested this and I have following comments:

-> lsmac does what described, shows that a macro is overloaded, but I think that it should be
shown at the other side of the name, just now the [*] at the left side and mixed with the other names,
 so it is difficult to see if some macro is overwritten, one has to look really carefully.

-> should one get a debug message when one overwrite a macro?, I do not get it.

-> perhaps it is known, but I have observed that if i overwrite a macro, let's say lsenv, and 
then I remove my version from my private macrolib, reload this macrolib and then reload the
macrolib containing the original lenv, env.py, this original lsen can not be loaded any more, I get
the error message like:

Door_issue930_1 [7]: relmaclib env
An error occurred while running Macro 'relmaclib(env) -> 2261d55e-c098-11e8-8f3f-901b0e40a03c':
'lsenv'

If I put lsenv again in my private macrolib and I reload it I get again the lsenv I defined, but from
 another macrolib I can not load it.

**Comment by cmft** [comment]
> -> lsmac does what described, shows that a macro is overloaded, but I think that it should be
> shown at the other side of the name, just now the [*] at the left side and mixed with the other names,
> so it is difficult to see if some macro is overwritten, one has to look really carefully.

Agree, It will be fixed

> -> should one get a debug message when one overwrite a macro?, I do not get it.

The debug message should be reported in the MacroServer
e.g.
```MainThread     DEBUG    2018-09-25 13:34:04,601 MS_cfalcon_1.MacroManager: Macro "mv" defined in "standard" macro library has been overwritten by "myascan" macro library```


> -> perhaps it is known, but I have observed that if i overwrite a macro, let's say lsenv, and
> then I remove my version from my private macrolib, reload this macrolib and then reload the
> macrolib containing the original lenv, env.py, this original lsen can not be loaded any more, I get
> the error message like:

I will test it.

**Comment by cmft** [comment]
Hi @teresanunez ,
I confirm that this is a bug (but not related with this feature):

> -> perhaps it is known, but I have observed that if i overwrite a macro, let's say lsenv, and
then I remove my version from my private macrolib, reload this macrolib and then reload the
macrolib containing the original lenv, env.py, this original lsen can not be loaded any more, I get
the error message like

It can be reproduced using develop. Could you report it?

**Comment by tiagocoutinho** [comment]
LGTM.
Since release branch is already created, @reszelaz will cherry-pick this commit directly and push it to the release branch

**Comment by reszelaz** [comment]
Thanks @cmft  and @tiagocoutinho!
I have merged it in the release-Jul19 branch. I think that this PR will get automatically closed whenever we merge the release branch into the develop branch. If not let close it manually after the release..

**Pull request merged**
